// generated by ui/scripts/gen-abis.mjs from ArtCoinsFactory.sol/ArtCoinsFactory.json, do not edit.
// regenerate: forge build (repo root) then cd ui && npm run gen:abi
export const factoryV1Abi = [
  {
    "type": "receive",
    "stateMutability": "payable"
  },
  {
    "type": "function",
    "name": "BPS",
    "inputs": [],
    "outputs": [
      {
        "name": "",
        "type": "uint256",
        "internalType": "uint256"
      }
    ],
    "stateMutability": "view"
  },
  {
    "type": "function",
    "name": "DEFAULT_TOKEN_SUPPLY",
    "inputs": [],
    "outputs": [
      {
        "name": "",
        "type": "uint256",
        "internalType": "uint256"
      }
    ],
    "stateMutability": "view"
  },
  {
    "type": "function",
    "name": "MAX_DEPLOY_FEE",
    "inputs": [],
    "outputs": [
      {
        "name": "",
        "type": "uint256",
        "internalType": "uint256"
      }
    ],
    "stateMutability": "view"
  },
  {
    "type": "function",
    "name": "MAX_EXTENSIONS",
    "inputs": [],
    "outputs": [
      {
        "name": "",
        "type": "uint256",
        "internalType": "uint256"
      }
    ],
    "stateMutability": "view"
  },
  {
    "type": "function",
    "name": "MAX_EXTENSION_BPS",
    "inputs": [],
    "outputs": [
      {
        "name": "",
        "type": "uint16",
        "internalType": "uint16"
      }
    ],
    "stateMutability": "view"
  },
  {
    "type": "function",
    "name": "MAX_PROTOCOL_FEE_BPS",
    "inputs": [],
    "outputs": [
      {
        "name": "",
        "type": "uint16",
        "internalType": "uint16"
      }
    ],
    "stateMutability": "view"
  },
  {
    "type": "function",
    "name": "MIN_TOKEN_SUPPLY",
    "inputs": [],
    "outputs": [
      {
        "name": "",
        "type": "uint256",
        "internalType": "uint256"
      }
    ],
    "stateMutability": "view"
  },
  {
    "type": "function",
    "name": "admins",
    "inputs": [
      {
        "name": "",
        "type": "address",
        "internalType": "address"
      }
    ],
    "outputs": [
      {
        "name": "",
        "type": "bool",
        "internalType": "bool"
      }
    ],
    "stateMutability": "view"
  },
  {
    "type": "function",
    "name": "claimTeamFees",
    "inputs": [
      {
        "name": "token",
        "type": "address",
        "internalType": "address"
      }
    ],
    "outputs": [],
    "stateMutability": "nonpayable"
  },
  {
    "type": "function",
    "name": "defaultProtocolFeeBps",
    "inputs": [],
    "outputs": [
      {
        "name": "",
        "type": "uint16",
        "internalType": "uint16"
      }
    ],
    "stateMutability": "view"
  },
  {
    "type": "function",
    "name": "deployFee",
    "inputs": [],
    "outputs": [
      {
        "name": "",
        "type": "uint256",
        "internalType": "uint256"
      }
    ],
    "stateMutability": "view"
  },
  {
    "type": "function",
    "name": "deployToken",
    "inputs": [
      {
        "name": "deploymentConfig",
        "type": "tuple",
        "internalType": "struct IArtCoinsFactory.DeploymentConfig",
        "components": [
          {
            "name": "tokenConfig",
            "type": "tuple",
            "internalType": "struct IArtCoinsFactory.TokenConfig",
            "components": [
              {
                "name": "tokenAdmin",
                "type": "address",
                "internalType": "address"
              },
              {
                "name": "name",
                "type": "string",
                "internalType": "string"
              },
              {
                "name": "symbol",
                "type": "string",
                "internalType": "string"
              },
              {
                "name": "salt",
                "type": "bytes32",
                "internalType": "bytes32"
              },
              {
                "name": "image",
                "type": "string",
                "internalType": "string"
              },
              {
                "name": "metadata",
                "type": "string",
                "internalType": "string"
              },
              {
                "name": "context",
                "type": "string",
                "internalType": "string"
              },
              {
                "name": "totalSupply",
                "type": "uint256",
                "internalType": "uint256"
              },
              {
                "name": "renderer",
                "type": "address",
                "internalType": "address"
              }
            ]
          },
          {
            "name": "poolConfig",
            "type": "tuple",
            "internalType": "struct IArtCoinsFactory.PoolConfig",
            "components": [
              {
                "name": "hook",
                "type": "address",
                "internalType": "address"
              },
              {
                "name": "pairedToken",
                "type": "address",
                "internalType": "address"
              },
              {
                "name": "tickIfToken0IsArtCoins",
                "type": "int24",
                "internalType": "int24"
              },
              {
                "name": "tickSpacing",
                "type": "int24",
                "internalType": "int24"
              },
              {
                "name": "poolData",
                "type": "bytes",
                "internalType": "bytes"
              }
            ]
          },
          {
            "name": "lockerConfig",
            "type": "tuple",
            "internalType": "struct IArtCoinsFactory.LockerConfig",
            "components": [
              {
                "name": "locker",
                "type": "address",
                "internalType": "address"
              },
              {
                "name": "rewardAdmins",
                "type": "address[]",
                "internalType": "address[]"
              },
              {
                "name": "rewardRecipients",
                "type": "address[]",
                "internalType": "address[]"
              },
              {
                "name": "rewardBps",
                "type": "uint16[]",
                "internalType": "uint16[]"
              },
              {
                "name": "tickLower",
                "type": "int24[]",
                "internalType": "int24[]"
              },
              {
                "name": "tickUpper",
                "type": "int24[]",
                "internalType": "int24[]"
              },
              {
                "name": "positionBps",
                "type": "uint16[]",
                "internalType": "uint16[]"
              },
              {
                "name": "lockerData",
                "type": "bytes",
                "internalType": "bytes"
              }
            ]
          },
          {
            "name": "mevModuleConfig",
            "type": "tuple",
            "internalType": "struct IArtCoinsFactory.MevModuleConfig",
            "components": [
              {
                "name": "mevModule",
                "type": "address",
                "internalType": "address"
              },
              {
                "name": "mevModuleData",
                "type": "bytes",
                "internalType": "bytes"
              }
            ]
          },
          {
            "name": "sniperFeeConfig",
            "type": "tuple",
            "internalType": "struct IArtCoinsFactory.SniperFeeConfig",
            "components": [
              {
                "name": "recipient",
                "type": "address",
                "internalType": "address"
              },
              {
                "name": "lockRecipient",
                "type": "bool",
                "internalType": "bool"
              }
            ]
          },
          {
            "name": "extensionConfigs",
            "type": "tuple[]",
            "internalType": "struct IArtCoinsFactory.ExtensionConfig[]",
            "components": [
              {
                "name": "extension",
                "type": "address",
                "internalType": "address"
              },
              {
                "name": "msgValue",
                "type": "uint256",
                "internalType": "uint256"
              },
              {
                "name": "extensionBps",
                "type": "uint16",
                "internalType": "uint16"
              },
              {
                "name": "extensionData",
                "type": "bytes",
                "internalType": "bytes"
              }
            ]
          }
        ]
      }
    ],
    "outputs": [
      {
        "name": "tokenAddress",
        "type": "address",
        "internalType": "address"
      }
    ],
    "stateMutability": "payable"
  },
  {
    "type": "function",
    "name": "deployTokenWithProtocolBps",
    "inputs": [
      {
        "name": "deploymentConfig",
        "type": "tuple",
        "internalType": "struct IArtCoinsFactory.DeploymentConfig",
        "components": [
          {
            "name": "tokenConfig",
            "type": "tuple",
            "internalType": "struct IArtCoinsFactory.TokenConfig",
            "components": [
              {
                "name": "tokenAdmin",
                "type": "address",
                "internalType": "address"
              },
              {
                "name": "name",
                "type": "string",
                "internalType": "string"
              },
              {
                "name": "symbol",
                "type": "string",
                "internalType": "string"
              },
              {
                "name": "salt",
                "type": "bytes32",
                "internalType": "bytes32"
              },
              {
                "name": "image",
                "type": "string",
                "internalType": "string"
              },
              {
                "name": "metadata",
                "type": "string",
                "internalType": "string"
              },
              {
                "name": "context",
                "type": "string",
                "internalType": "string"
              },
              {
                "name": "totalSupply",
                "type": "uint256",
                "internalType": "uint256"
              },
              {
                "name": "renderer",
                "type": "address",
                "internalType": "address"
              }
            ]
          },
          {
            "name": "poolConfig",
            "type": "tuple",
            "internalType": "struct IArtCoinsFactory.PoolConfig",
            "components": [
              {
                "name": "hook",
                "type": "address",
                "internalType": "address"
              },
              {
                "name": "pairedToken",
                "type": "address",
                "internalType": "address"
              },
              {
                "name": "tickIfToken0IsArtCoins",
                "type": "int24",
                "internalType": "int24"
              },
              {
                "name": "tickSpacing",
                "type": "int24",
                "internalType": "int24"
              },
              {
                "name": "poolData",
                "type": "bytes",
                "internalType": "bytes"
              }
            ]
          },
          {
            "name": "lockerConfig",
            "type": "tuple",
            "internalType": "struct IArtCoinsFactory.LockerConfig",
            "components": [
              {
                "name": "locker",
                "type": "address",
                "internalType": "address"
              },
              {
                "name": "rewardAdmins",
                "type": "address[]",
                "internalType": "address[]"
              },
              {
                "name": "rewardRecipients",
                "type": "address[]",
                "internalType": "address[]"
              },
              {
                "name": "rewardBps",
                "type": "uint16[]",
                "internalType": "uint16[]"
              },
              {
                "name": "tickLower",
                "type": "int24[]",
                "internalType": "int24[]"
              },
              {
                "name": "tickUpper",
                "type": "int24[]",
                "internalType": "int24[]"
              },
              {
                "name": "positionBps",
                "type": "uint16[]",
                "internalType": "uint16[]"
              },
              {
                "name": "lockerData",
                "type": "bytes",
                "internalType": "bytes"
              }
            ]
          },
          {
            "name": "mevModuleConfig",
            "type": "tuple",
            "internalType": "struct IArtCoinsFactory.MevModuleConfig",
            "components": [
              {
                "name": "mevModule",
                "type": "address",
                "internalType": "address"
              },
              {
                "name": "mevModuleData",
                "type": "bytes",
                "internalType": "bytes"
              }
            ]
          },
          {
            "name": "sniperFeeConfig",
            "type": "tuple",
            "internalType": "struct IArtCoinsFactory.SniperFeeConfig",
            "components": [
              {
                "name": "recipient",
                "type": "address",
                "internalType": "address"
              },
              {
                "name": "lockRecipient",
                "type": "bool",
                "internalType": "bool"
              }
            ]
          },
          {
            "name": "extensionConfigs",
            "type": "tuple[]",
            "internalType": "struct IArtCoinsFactory.ExtensionConfig[]",
            "components": [
              {
                "name": "extension",
                "type": "address",
                "internalType": "address"
              },
              {
                "name": "msgValue",
                "type": "uint256",
                "internalType": "uint256"
              },
              {
                "name": "extensionBps",
                "type": "uint16",
                "internalType": "uint16"
              },
              {
                "name": "extensionData",
                "type": "bytes",
                "internalType": "bytes"
              }
            ]
          }
        ]
      },
      {
        "name": "protocolBpsOverride",
        "type": "uint16",
        "internalType": "uint16"
      }
    ],
    "outputs": [
      {
        "name": "tokenAddress",
        "type": "address",
        "internalType": "address"
      }
    ],
    "stateMutability": "payable"
  },
  {
    "type": "function",
    "name": "deployTokenWithProtocolBpsAndTax",
    "inputs": [
      {
        "name": "deploymentConfig",
        "type": "tuple",
        "internalType": "struct IArtCoinsFactory.DeploymentConfig",
        "components": [
          {
            "name": "tokenConfig",
            "type": "tuple",
            "internalType": "struct IArtCoinsFactory.TokenConfig",
            "components": [
              {
                "name": "tokenAdmin",
                "type": "address",
                "internalType": "address"
              },
              {
                "name": "name",
                "type": "string",
                "internalType": "string"
              },
              {
                "name": "symbol",
                "type": "string",
                "internalType": "string"
              },
              {
                "name": "salt",
                "type": "bytes32",
                "internalType": "bytes32"
              },
              {
                "name": "image",
                "type": "string",
                "internalType": "string"
              },
              {
                "name": "metadata",
                "type": "string",
                "internalType": "string"
              },
              {
                "name": "context",
                "type": "string",
                "internalType": "string"
              },
              {
                "name": "totalSupply",
                "type": "uint256",
                "internalType": "uint256"
              },
              {
                "name": "renderer",
                "type": "address",
                "internalType": "address"
              }
            ]
          },
          {
            "name": "poolConfig",
            "type": "tuple",
            "internalType": "struct IArtCoinsFactory.PoolConfig",
            "components": [
              {
                "name": "hook",
                "type": "address",
                "internalType": "address"
              },
              {
                "name": "pairedToken",
                "type": "address",
                "internalType": "address"
              },
              {
                "name": "tickIfToken0IsArtCoins",
                "type": "int24",
                "internalType": "int24"
              },
              {
                "name": "tickSpacing",
                "type": "int24",
                "internalType": "int24"
              },
              {
                "name": "poolData",
                "type": "bytes",
                "internalType": "bytes"
              }
            ]
          },
          {
            "name": "lockerConfig",
            "type": "tuple",
            "internalType": "struct IArtCoinsFactory.LockerConfig",
            "components": [
              {
                "name": "locker",
                "type": "address",
                "internalType": "address"
              },
              {
                "name": "rewardAdmins",
                "type": "address[]",
                "internalType": "address[]"
              },
              {
                "name": "rewardRecipients",
                "type": "address[]",
                "internalType": "address[]"
              },
              {
                "name": "rewardBps",
                "type": "uint16[]",
                "internalType": "uint16[]"
              },
              {
                "name": "tickLower",
                "type": "int24[]",
                "internalType": "int24[]"
              },
              {
                "name": "tickUpper",
                "type": "int24[]",
                "internalType": "int24[]"
              },
              {
                "name": "positionBps",
                "type": "uint16[]",
                "internalType": "uint16[]"
              },
              {
                "name": "lockerData",
                "type": "bytes",
                "internalType": "bytes"
              }
            ]
          },
          {
            "name": "mevModuleConfig",
            "type": "tuple",
            "internalType": "struct IArtCoinsFactory.MevModuleConfig",
            "components": [
              {
                "name": "mevModule",
                "type": "address",
                "internalType": "address"
              },
              {
                "name": "mevModuleData",
                "type": "bytes",
                "internalType": "bytes"
              }
            ]
          },
          {
            "name": "sniperFeeConfig",
            "type": "tuple",
            "internalType": "struct IArtCoinsFactory.SniperFeeConfig",
            "components": [
              {
                "name": "recipient",
                "type": "address",
                "internalType": "address"
              },
              {
                "name": "lockRecipient",
                "type": "bool",
                "internalType": "bool"
              }
            ]
          },
          {
            "name": "extensionConfigs",
            "type": "tuple[]",
            "internalType": "struct IArtCoinsFactory.ExtensionConfig[]",
            "components": [
              {
                "name": "extension",
                "type": "address",
                "internalType": "address"
              },
              {
                "name": "msgValue",
                "type": "uint256",
                "internalType": "uint256"
              },
              {
                "name": "extensionBps",
                "type": "uint16",
                "internalType": "uint16"
              },
              {
                "name": "extensionData",
                "type": "bytes",
                "internalType": "bytes"
              }
            ]
          }
        ]
      },
      {
        "name": "protocolBpsOverride",
        "type": "uint16",
        "internalType": "uint16"
      },
      {
        "name": "taxConfig",
        "type": "tuple",
        "internalType": "struct TaxConfig",
        "components": [
          {
            "name": "enabled",
            "type": "bool",
            "internalType": "bool"
          },
          {
            "name": "taxBps",
            "type": "uint16",
            "internalType": "uint16"
          },
          {
            "name": "taxBpsMax",
            "type": "uint16",
            "internalType": "uint16"
          },
          {
            "name": "burnAddress",
            "type": "address",
            "internalType": "address"
          },
          {
            "name": "poolManager",
            "type": "address",
            "internalType": "address"
          },
          {
            "name": "canonicalHook",
            "type": "address",
            "internalType": "address"
          },
          {
            "name": "pairedToken",
            "type": "address",
            "internalType": "address"
          },
          {
            "name": "canonicalPoolFee",
            "type": "uint24",
            "internalType": "uint24"
          },
          {
            "name": "canonicalTickSpacing",
            "type": "int24",
            "internalType": "int24"
          },
          {
            "name": "exempt",
            "type": "address[]",
            "internalType": "address[]"
          },
          {
            "name": "venues",
            "type": "tuple[]",
            "internalType": "struct TaxVenue[]",
            "components": [
              {
                "name": "kind",
                "type": "uint8",
                "internalType": "uint8"
              },
              {
                "name": "factory",
                "type": "address",
                "internalType": "address"
              },
              {
                "name": "initCodeHash",
                "type": "bytes32",
                "internalType": "bytes32"
              },
              {
                "name": "counterToken",
                "type": "address",
                "internalType": "address"
              },
              {
                "name": "v3Fee",
                "type": "uint24",
                "internalType": "uint24"
              }
            ]
          }
        ]
      }
    ],
    "outputs": [
      {
        "name": "tokenAddress",
        "type": "address",
        "internalType": "address"
      }
    ],
    "stateMutability": "payable"
  },
  {
    "type": "function",
    "name": "deploymentInfoForToken",
    "inputs": [
      {
        "name": "token",
        "type": "address",
        "internalType": "address"
      }
    ],
    "outputs": [
      {
        "name": "token",
        "type": "address",
        "internalType": "address"
      },
      {
        "name": "hook",
        "type": "address",
        "internalType": "address"
      },
      {
        "name": "locker",
        "type": "address",
        "internalType": "address"
      }
    ],
    "stateMutability": "view"
  },
  {
    "type": "function",
    "name": "deprecated",
    "inputs": [],
    "outputs": [
      {
        "name": "",
        "type": "bool",
        "internalType": "bool"
      }
    ],
    "stateMutability": "view"
  },
  {
    "type": "function",
    "name": "enabledExtensions",
    "inputs": [
      {
        "name": "extension",
        "type": "address",
        "internalType": "address"
      }
    ],
    "outputs": [
      {
        "name": "enabled",
        "type": "bool",
        "internalType": "bool"
      }
    ],
    "stateMutability": "view"
  },
  {
    "type": "function",
    "name": "enabledHooks",
    "inputs": [
      {
        "name": "hook",
        "type": "address",
        "internalType": "address"
      }
    ],
    "outputs": [
      {
        "name": "enabled",
        "type": "bool",
        "internalType": "bool"
      }
    ],
    "stateMutability": "view"
  },
  {
    "type": "function",
    "name": "enabledLockers",
    "inputs": [
      {
        "name": "locker",
        "type": "address",
        "internalType": "address"
      },
      {
        "name": "hook",
        "type": "address",
        "internalType": "address"
      }
    ],
    "outputs": [
      {
        "name": "enabled",
        "type": "bool",
        "internalType": "bool"
      }
    ],
    "stateMutability": "view"
  },
  {
    "type": "function",
    "name": "enabledMevModules",
    "inputs": [
      {
        "name": "mevModule",
        "type": "address",
        "internalType": "address"
      }
    ],
    "outputs": [
      {
        "name": "enabled",
        "type": "bool",
        "internalType": "bool"
      }
    ],
    "stateMutability": "view"
  },
  {
    "type": "function",
    "name": "owner",
    "inputs": [],
    "outputs": [
      {
        "name": "",
        "type": "address",
        "internalType": "address"
      }
    ],
    "stateMutability": "view"
  },
  {
    "type": "function",
    "name": "recoverETH",
    "inputs": [
      {
        "name": "to",
        "type": "address",
        "internalType": "address payable"
      }
    ],
    "outputs": [],
    "stateMutability": "nonpayable"
  },
  {
    "type": "function",
    "name": "renounceOwnership",
    "inputs": [],
    "outputs": [],
    "stateMutability": "nonpayable"
  },
  {
    "type": "function",
    "name": "setAdmin",
    "inputs": [
      {
        "name": "admin",
        "type": "address",
        "internalType": "address"
      },
      {
        "name": "enabled",
        "type": "bool",
        "internalType": "bool"
      }
    ],
    "outputs": [],
    "stateMutability": "nonpayable"
  },
  {
    "type": "function",
    "name": "setDefaultProtocolFeeBps",
    "inputs": [
      {
        "name": "defaultProtocolFeeBps_",
        "type": "uint16",
        "internalType": "uint16"
      }
    ],
    "outputs": [],
    "stateMutability": "nonpayable"
  },
  {
    "type": "function",
    "name": "setDeployFee",
    "inputs": [
      {
        "name": "deployFee_",
        "type": "uint256",
        "internalType": "uint256"
      }
    ],
    "outputs": [],
    "stateMutability": "nonpayable"
  },
  {
    "type": "function",
    "name": "setDeprecated",
    "inputs": [
      {
        "name": "deprecated_",
        "type": "bool",
        "internalType": "bool"
      }
    ],
    "outputs": [],
    "stateMutability": "nonpayable"
  },
  {
    "type": "function",
    "name": "setExtension",
    "inputs": [
      {
        "name": "extension",
        "type": "address",
        "internalType": "address"
      },
      {
        "name": "enabled",
        "type": "bool",
        "internalType": "bool"
      }
    ],
    "outputs": [],
    "stateMutability": "nonpayable"
  },
  {
    "type": "function",
    "name": "setHook",
    "inputs": [
      {
        "name": "hook",
        "type": "address",
        "internalType": "address"
      },
      {
        "name": "enabled",
        "type": "bool",
        "internalType": "bool"
      }
    ],
    "outputs": [],
    "stateMutability": "nonpayable"
  },
  {
    "type": "function",
    "name": "setLocker",
    "inputs": [
      {
        "name": "locker",
        "type": "address",
        "internalType": "address"
      },
      {
        "name": "hook",
        "type": "address",
        "internalType": "address"
      },
      {
        "name": "enabled",
        "type": "bool",
        "internalType": "bool"
      }
    ],
    "outputs": [],
    "stateMutability": "nonpayable"
  },
  {
    "type": "function",
    "name": "setMevModule",
    "inputs": [
      {
        "name": "mevModule",
        "type": "address",
        "internalType": "address"
      },
      {
        "name": "enabled",
        "type": "bool",
        "internalType": "bool"
      }
    ],
    "outputs": [],
    "stateMutability": "nonpayable"
  },
  {
    "type": "function",
    "name": "setTeamFeeRecipient",
    "inputs": [
      {
        "name": "teamFeeRecipient_",
        "type": "address",
        "internalType": "address"
      }
    ],
    "outputs": [],
    "stateMutability": "nonpayable"
  },
  {
    "type": "function",
    "name": "teamFeeRecipient",
    "inputs": [],
    "outputs": [
      {
        "name": "",
        "type": "address",
        "internalType": "address"
      }
    ],
    "stateMutability": "view"
  },
  {
    "type": "function",
    "name": "tokenDeploymentInfo",
    "inputs": [
      {
        "name": "token",
        "type": "address",
        "internalType": "address"
      }
    ],
    "outputs": [
      {
        "name": "",
        "type": "tuple",
        "internalType": "struct IArtCoinsFactory.DeploymentInfo",
        "components": [
          {
            "name": "token",
            "type": "address",
            "internalType": "address"
          },
          {
            "name": "hook",
            "type": "address",
            "internalType": "address"
          },
          {
            "name": "locker",
            "type": "address",
            "internalType": "address"
          },
          {
            "name": "extensions",
            "type": "address[]",
            "internalType": "address[]"
          }
        ]
      }
    ],
    "stateMutability": "view"
  },
  {
    "type": "function",
    "name": "transferOwnership",
    "inputs": [
      {
        "name": "newOwner",
        "type": "address",
        "internalType": "address"
      }
    ],
    "outputs": [],
    "stateMutability": "nonpayable"
  },
  {
    "type": "function",
    "name": "version",
    "inputs": [],
    "outputs": [
      {
        "name": "",
        "type": "string",
        "internalType": "string"
      }
    ],
    "stateMutability": "view"
  },
  {
    "type": "event",
    "name": "ClaimTeamFees",
    "inputs": [
      {
        "name": "token",
        "type": "address",
        "indexed": true,
        "internalType": "address"
      },
      {
        "name": "recipient",
        "type": "address",
        "indexed": true,
        "internalType": "address"
      },
      {
        "name": "amount",
        "type": "uint256",
        "indexed": false,
        "internalType": "uint256"
      }
    ],
    "anonymous": false
  },
  {
    "type": "event",
    "name": "DefaultProtocolFeeBpsUpdated",
    "inputs": [
      {
        "name": "oldBps",
        "type": "uint16",
        "indexed": false,
        "internalType": "uint16"
      },
      {
        "name": "newBps",
        "type": "uint16",
        "indexed": false,
        "internalType": "uint16"
      }
    ],
    "anonymous": false
  },
  {
    "type": "event",
    "name": "DeployFeePaid",
    "inputs": [
      {
        "name": "recipient",
        "type": "address",
        "indexed": true,
        "internalType": "address"
      },
      {
        "name": "amount",
        "type": "uint256",
        "indexed": false,
        "internalType": "uint256"
      }
    ],
    "anonymous": false
  },
  {
    "type": "event",
    "name": "DeployFeeUpdated",
    "inputs": [
      {
        "name": "oldFee",
        "type": "uint256",
        "indexed": false,
        "internalType": "uint256"
      },
      {
        "name": "newFee",
        "type": "uint256",
        "indexed": false,
        "internalType": "uint256"
      }
    ],
    "anonymous": false
  },
  {
    "type": "event",
    "name": "ExtensionTriggered",
    "inputs": [
      {
        "name": "extension",
        "type": "address",
        "indexed": false,
        "internalType": "address"
      },
      {
        "name": "extensionSupply",
        "type": "uint256",
        "indexed": false,
        "internalType": "uint256"
      },
      {
        "name": "msgValue",
        "type": "uint256",
        "indexed": false,
        "internalType": "uint256"
      }
    ],
    "anonymous": false
  },
  {
    "type": "event",
    "name": "OwnershipTransferred",
    "inputs": [
      {
        "name": "previousOwner",
        "type": "address",
        "indexed": true,
        "internalType": "address"
      },
      {
        "name": "newOwner",
        "type": "address",
        "indexed": true,
        "internalType": "address"
      }
    ],
    "anonymous": false
  },
  {
    "type": "event",
    "name": "RecoverEth",
    "inputs": [
      {
        "name": "recipient",
        "type": "address",
        "indexed": true,
        "internalType": "address"
      },
      {
        "name": "amount",
        "type": "uint256",
        "indexed": false,
        "internalType": "uint256"
      }
    ],
    "anonymous": false
  },
  {
    "type": "event",
    "name": "SetAdmin",
    "inputs": [
      {
        "name": "admin",
        "type": "address",
        "indexed": true,
        "internalType": "address"
      },
      {
        "name": "enabled",
        "type": "bool",
        "indexed": false,
        "internalType": "bool"
      }
    ],
    "anonymous": false
  },
  {
    "type": "event",
    "name": "SetDeprecated",
    "inputs": [
      {
        "name": "deprecated",
        "type": "bool",
        "indexed": false,
        "internalType": "bool"
      }
    ],
    "anonymous": false
  },
  {
    "type": "event",
    "name": "SetExtension",
    "inputs": [
      {
        "name": "extension",
        "type": "address",
        "indexed": false,
        "internalType": "address"
      },
      {
        "name": "enabled",
        "type": "bool",
        "indexed": false,
        "internalType": "bool"
      }
    ],
    "anonymous": false
  },
  {
    "type": "event",
    "name": "SetHook",
    "inputs": [
      {
        "name": "hook",
        "type": "address",
        "indexed": false,
        "internalType": "address"
      },
      {
        "name": "enabled",
        "type": "bool",
        "indexed": false,
        "internalType": "bool"
      }
    ],
    "anonymous": false
  },
  {
    "type": "event",
    "name": "SetLocker",
    "inputs": [
      {
        "name": "locker",
        "type": "address",
        "indexed": false,
        "internalType": "address"
      },
      {
        "name": "hook",
        "type": "address",
        "indexed": false,
        "internalType": "address"
      },
      {
        "name": "enabled",
        "type": "bool",
        "indexed": false,
        "internalType": "bool"
      }
    ],
    "anonymous": false
  },
  {
    "type": "event",
    "name": "SetMevModule",
    "inputs": [
      {
        "name": "mevModule",
        "type": "address",
        "indexed": false,
        "internalType": "address"
      },
      {
        "name": "enabled",
        "type": "bool",
        "indexed": false,
        "internalType": "bool"
      }
    ],
    "anonymous": false
  },
  {
    "type": "event",
    "name": "SetTeamFeeRecipient",
    "inputs": [
      {
        "name": "oldTeamFeeRecipient",
        "type": "address",
        "indexed": false,
        "internalType": "address"
      },
      {
        "name": "newTeamFeeRecipient",
        "type": "address",
        "indexed": false,
        "internalType": "address"
      }
    ],
    "anonymous": false
  },
  {
    "type": "event",
    "name": "TokenCreated",
    "inputs": [
      {
        "name": "msgSender",
        "type": "address",
        "indexed": false,
        "internalType": "address"
      },
      {
        "name": "tokenAddress",
        "type": "address",
        "indexed": true,
        "internalType": "address"
      },
      {
        "name": "tokenAdmin",
        "type": "address",
        "indexed": true,
        "internalType": "address"
      },
      {
        "name": "tokenImage",
        "type": "string",
        "indexed": false,
        "internalType": "string"
      },
      {
        "name": "tokenName",
        "type": "string",
        "indexed": false,
        "internalType": "string"
      },
      {
        "name": "tokenSymbol",
        "type": "string",
        "indexed": false,
        "internalType": "string"
      },
      {
        "name": "tokenMetadata",
        "type": "string",
        "indexed": false,
        "internalType": "string"
      },
      {
        "name": "tokenContext",
        "type": "string",
        "indexed": false,
        "internalType": "string"
      },
      {
        "name": "startingTick",
        "type": "int24",
        "indexed": false,
        "internalType": "int24"
      },
      {
        "name": "poolHook",
        "type": "address",
        "indexed": false,
        "internalType": "address"
      },
      {
        "name": "poolId",
        "type": "bytes32",
        "indexed": false,
        "internalType": "PoolId"
      },
      {
        "name": "pairedToken",
        "type": "address",
        "indexed": false,
        "internalType": "address"
      },
      {
        "name": "locker",
        "type": "address",
        "indexed": false,
        "internalType": "address"
      },
      {
        "name": "mevModule",
        "type": "address",
        "indexed": false,
        "internalType": "address"
      },
      {
        "name": "extensionsSupply",
        "type": "uint256",
        "indexed": false,
        "internalType": "uint256"
      },
      {
        "name": "extensions",
        "type": "address[]",
        "indexed": false,
        "internalType": "address[]"
      }
    ],
    "anonymous": false
  },
  {
    "type": "error",
    "name": "DeployFeeTooHigh",
    "inputs": []
  },
  {
    "type": "error",
    "name": "Deprecated",
    "inputs": []
  },
  {
    "type": "error",
    "name": "EthTransferFailed",
    "inputs": []
  },
  {
    "type": "error",
    "name": "ExtensionMsgValueMismatch",
    "inputs": []
  },
  {
    "type": "error",
    "name": "ExtensionNotEnabled",
    "inputs": []
  },
  {
    "type": "error",
    "name": "HookNotEnabled",
    "inputs": []
  },
  {
    "type": "error",
    "name": "InvalidExtension",
    "inputs": []
  },
  {
    "type": "error",
    "name": "InvalidHook",
    "inputs": []
  },
  {
    "type": "error",
    "name": "InvalidLocker",
    "inputs": []
  },
  {
    "type": "error",
    "name": "InvalidMevModule",
    "inputs": []
  },
  {
    "type": "error",
    "name": "LockerNotEnabled",
    "inputs": []
  },
  {
    "type": "error",
    "name": "MaxExtensionBpsExceeded",
    "inputs": []
  },
  {
    "type": "error",
    "name": "MaxExtensionsExceeded",
    "inputs": []
  },
  {
    "type": "error",
    "name": "MevModuleNotEnabled",
    "inputs": []
  },
  {
    "type": "error",
    "name": "NotFound",
    "inputs": []
  },
  {
    "type": "error",
    "name": "OwnableInvalidOwner",
    "inputs": [
      {
        "name": "owner",
        "type": "address",
        "internalType": "address"
      }
    ]
  },
  {
    "type": "error",
    "name": "OwnableUnauthorizedAccount",
    "inputs": [
      {
        "name": "account",
        "type": "address",
        "internalType": "address"
      }
    ]
  },
  {
    "type": "error",
    "name": "ProjectSideBpsMismatch",
    "inputs": []
  },
  {
    "type": "error",
    "name": "ProtocolFeeBpsTooHigh",
    "inputs": []
  },
  {
    "type": "error",
    "name": "ReentrancyGuardReentrantCall",
    "inputs": []
  },
  {
    "type": "error",
    "name": "SafeERC20FailedOperation",
    "inputs": [
      {
        "name": "token",
        "type": "address",
        "internalType": "address"
      }
    ]
  },
  {
    "type": "error",
    "name": "TeamFeeRecipientNotSet",
    "inputs": []
  },
  {
    "type": "error",
    "name": "TotalSupplyTooLow",
    "inputs": []
  },
  {
    "type": "error",
    "name": "Unauthorized",
    "inputs": []
  },
  {
    "type": "error",
    "name": "ZeroAddress",
    "inputs": []
  }
] as const;
