// Generates ui/src/lib/abi/{v1,v2}/*.ts from forge artifacts so the ui abi cannot drift from the contracts.
//
//   forge build --skip "test/**" --skip "src/v2/hooks/**"     (from the repo root)
//   cd ui && npm run gen:abi            write the files
//   cd ui && npm run check:abi          exit 1 when a committed file differs from the artifacts
//
// v2 entries come from the frozen interfaces (the deployed contracts implement them exactly),
// v1 entries from the contracts of the current mainnet stack (factory 0x4959...).
import { readFileSync, writeFileSync, existsSync, mkdirSync } from 'node:fs';
import { dirname, join, resolve } from 'node:path';
import { fileURLToPath } from 'node:url';

const here = dirname(fileURLToPath(import.meta.url));
const root = resolve(here, '../..');
const out = join(root, 'foundry-out');
const dest = resolve(here, '../src/lib/abi');
const check = process.argv.includes('--check');

/** [group, file name, artifact dir (the .sol file), contract name, export name] */
const TARGETS = [
  ['v2', 'factory', 'IArtCoinsFactoryV2.sol', 'IArtCoinsFactoryV2', 'factoryV2Abi'],
  ['v2', 'hook', 'IArtCoinsHookV2.sol', 'IArtCoinsHookV2', 'hookV2Abi'],
  ['v2', 'token', 'IArtCoinsTokenV2.sol', 'IArtCoinsTokenV2', 'tokenV2Abi'],
  ['v2', 'locker', 'IArtCoinsLpLockerV2.sol', 'IArtCoinsLpLockerV2', 'lockerV2Abi'],
  ['v2', 'mevSkim', 'IArtCoinsMevSkimV2.sol', 'IArtCoinsMevSkimV2', 'mevSkimV2Abi'],
  ['v2', 'escrow', 'IArtCoinsFeeEscrowV2.sol', 'IArtCoinsFeeEscrowV2', 'escrowV2Abi'],
  ['v2', 'devBuy', 'IArtCoinsUniv4EthDevBuyV2.sol', 'IArtCoinsUniv4EthDevBuyV2', 'devBuyV2Abi'],
  ['v2', 'vault', 'IArtCoinsVaultV2.sol', 'IArtCoinsVaultV2', 'vaultV2Abi'],
  ['v2', 'airdrop', 'IArtCoinsAirdropV2.sol', 'IArtCoinsAirdropV2', 'airdropV2Abi'],
  ['v1', 'factory', 'ArtCoinsFactory.sol', 'ArtCoinsFactory', 'factoryV1Abi'],
  ['v1', 'hook', 'ArtCoinsHookSkimFee.sol', 'ArtCoinsHookSkimFee', 'hookV1Abi'],
  ['v1', 'token', 'ArtCoinsToken.sol', 'ArtCoinsToken', 'tokenV1Abi'],
  ['v1', 'locker', 'ArtCoinsLpLocker.sol', 'ArtCoinsLpLocker', 'lockerV1Abi'],
  ['v1', 'mevLinearSkim', 'ArtCoinsMevLinearSkim.sol', 'ArtCoinsMevLinearSkim', 'mevLinearSkimV1Abi'],
];

let drift = 0;
for (const [group, name, dir, contract, exp] of TARGETS) {
  const artifact = join(out, dir, `${contract}.json`);
  if (!existsSync(artifact)) {
    console.error(`missing artifact ${artifact}; run forge build first`);
    process.exit(2);
  }
  const abi = JSON.parse(readFileSync(artifact, 'utf8')).abi.filter((x) => x.type !== 'constructor');
  const body =
    `// generated by ui/scripts/gen-abis.mjs from ${dir}/${contract}.json, do not edit.\n` +
    `// regenerate: forge build (repo root) then cd ui && npm run gen:abi\n` +
    `export const ${exp} = ${JSON.stringify(abi, null, 2)} as const;\n`;
  const file = join(dest, group, `${name}.ts`);
  mkdirSync(dirname(file), { recursive: true });
  const prev = existsSync(file) ? readFileSync(file, 'utf8') : null;
  if (check) {
    if (prev !== body) {
      drift++;
      console.error(`drift: ${file}`);
    }
  } else if (prev !== body) {
    writeFileSync(file, body);
    console.log(`wrote ${group}/${name}.ts (${abi.length} items)`);
  }
}
if (check && drift) process.exit(1);
if (check) console.log('abi files match artifacts');
