// Hand-written ABI fragments for contracts that are NOT generated by
// script-js/generate-abis.mjs, because their source either isn't in this
// repo at all, or doesn't compile standalone with this repo's pinned
// solc/remappings. See script-js/generate-abis.mjs's header comment for
// the two v4-periphery contracts (StateView, V4Quoter) that DO compile
// cleanly and are generated instead — only what's listed below stays here.
//
// Each entry documents why it can't be generated. Keep these subsets
// curated and minimal, same as before this file existed.

// ─── Uniswap Permit2 ────────────────────────────────────────────────────
// lib/permit2/src/Permit2.sol pins `pragma solidity 0.8.17;` (exact, not
// `^0.8.17`), which hard-conflicts with this repo's pinned `solc = "0.8.26"`
// (foundry.toml). It cannot be compiled in the same solc invocation as the
// rest of this repo, hand-written it stays.
export const permit2Abi = [
  {
    type: 'function',
    name: 'allowance',
    inputs: [
      { name: 'owner', type: 'address' },
      { name: 'token', type: 'address' },
      { name: 'spender', type: 'address' },
    ],
    outputs: [
      { name: 'amount', type: 'uint160' },
      { name: 'expiration', type: 'uint48' },
      { name: 'nonce', type: 'uint48' },
    ],
    stateMutability: 'view',
  },
  {
    type: 'function',
    name: 'approve',
    inputs: [
      { name: 'token', type: 'address' },
      { name: 'spender', type: 'address' },
      { name: 'amount', type: 'uint160' },
      { name: 'expiration', type: 'uint48' },
    ],
    outputs: [],
    stateMutability: 'nonpayable',
  },
] as const;

// ─── Universal Router — execute entry point ────────────────────────────
// lib/universal-router's own remappings.txt points imports like
// `@uniswap/v3-periphery/` at paths relative to ITS OWN root (and a couple
// at `node_modules/`, which isn't populated), not this repo's root or
// implicit lib-name resolution. Reproducing Foundry's full nested-remapping
// resolution (each dependency can carry its own remappings.txt/foundry.toml)
// was judged not worth it for one function signature — hand-written it stays.
export const universalRouterAbi = [
  {
    type: 'function',
    name: 'execute',
    inputs: [
      { name: 'commands', type: 'bytes' },
      { name: 'inputs', type: 'bytes[]' },
      { name: 'deadline', type: 'uint256' },
    ],
    outputs: [],
    stateMutability: 'payable',
  },
] as const;

// ─── ReferralPayout ─────────────────────────────────────────────────────
// There is NO `ReferralPayout` contract anywhere in this repo's src/ or
// lib/. src/hooks/interfaces/IArtCoinsHookSkimFee.sol only declares the
// minimal caller-side interface the hook needs:
//   interface IReferralPayoutForHook { function notify(address) external payable; }
// The real ReferralPayout contract (with `balances`, `claim`, `claimFor`,
// `ReferralCredited`/`ReferralClaimed` events, etc.) is deployed and
// maintained OUTSIDE this repo — test/ only has mocks
// (MockReferralPayout / RejectingReferralPayout) that stub `notify`.
// This ABI is inherently unverifiable against artcoins' own source; treat
// any change to it as a note to sync from wherever ReferralPayout's real
// source lives, not from this repo.
export const referralPayoutAbi = [
  { type: 'function', name: 'balances', inputs: [{ type: 'address' }], outputs: [{ type: 'uint256' }], stateMutability: 'view' },
  { type: 'function', name: 'claim', inputs: [], outputs: [], stateMutability: 'nonpayable' },
  { type: 'function', name: 'claimFor', inputs: [{ name: 'referrer', type: 'address' }], outputs: [], stateMutability: 'nonpayable' },
  // Events (for future indexer integration; not consumed by the page today).
  { type: 'event', name: 'ReferralCredited', inputs: [{ name: 'referrer', type: 'address', indexed: true }, { name: 'amount', type: 'uint256', indexed: false }] },
  { type: 'event', name: 'ReferralClaimed', inputs: [{ name: 'referrer', type: 'address', indexed: true }, { name: 'amount', type: 'uint256', indexed: false }] },
  // Errors surfaced from claim attempts (best-effort decode in the UI).
  { type: 'error', name: 'TransferFailed', inputs: [{ type: 'address' }, { type: 'uint256' }] },
  { type: 'error', name: 'NothingToClaim', inputs: [] },
] as const;
