// generated by script-js/gen-abis.mjs from IArtCoinsAirdropV2.sol/IArtCoinsAirdropV2.json, do not edit.
// regenerate: forge build (repo root) then cd script-js && npm run gen:abi
export const airdropV2Abi = [
  {
    "type": "function",
    "name": "amountAvailableToClaim",
    "inputs": [
      {
        "name": "token",
        "type": "address",
        "internalType": "address"
      },
      {
        "name": "index",
        "type": "uint256",
        "internalType": "uint256"
      },
      {
        "name": "recipient",
        "type": "address",
        "internalType": "address"
      },
      {
        "name": "allocatedAmount",
        "type": "uint256",
        "internalType": "uint256"
      }
    ],
    "outputs": [
      {
        "name": "",
        "type": "uint256",
        "internalType": "uint256"
      }
    ],
    "stateMutability": "view"
  },
  {
    "type": "function",
    "name": "claim",
    "inputs": [
      {
        "name": "token",
        "type": "address",
        "internalType": "address"
      },
      {
        "name": "index",
        "type": "uint256",
        "internalType": "uint256"
      },
      {
        "name": "recipient",
        "type": "address",
        "internalType": "address"
      },
      {
        "name": "allocatedAmount",
        "type": "uint256",
        "internalType": "uint256"
      },
      {
        "name": "proof",
        "type": "bytes32[]",
        "internalType": "bytes32[]"
      }
    ],
    "outputs": [],
    "stateMutability": "nonpayable"
  },
  {
    "type": "function",
    "name": "constantsHash",
    "inputs": [],
    "outputs": [
      {
        "name": "",
        "type": "bytes32",
        "internalType": "bytes32"
      }
    ],
    "stateMutability": "pure"
  },
  {
    "type": "function",
    "name": "leafClaimed",
    "inputs": [
      {
        "name": "token",
        "type": "address",
        "internalType": "address"
      },
      {
        "name": "index",
        "type": "uint256",
        "internalType": "uint256"
      },
      {
        "name": "recipient",
        "type": "address",
        "internalType": "address"
      },
      {
        "name": "allocatedAmount",
        "type": "uint256",
        "internalType": "uint256"
      }
    ],
    "outputs": [
      {
        "name": "",
        "type": "uint256",
        "internalType": "uint256"
      }
    ],
    "stateMutability": "view"
  },
  {
    "type": "function",
    "name": "leafHash",
    "inputs": [
      {
        "name": "account",
        "type": "address",
        "internalType": "address"
      },
      {
        "name": "amount",
        "type": "uint256",
        "internalType": "uint256"
      }
    ],
    "outputs": [
      {
        "name": "",
        "type": "bytes32",
        "internalType": "bytes32"
      }
    ],
    "stateMutability": "pure"
  },
  {
    "type": "function",
    "name": "receiveTokens",
    "inputs": [
      {
        "name": "config",
        "type": "tuple",
        "internalType": "struct IArtCoinsFactoryV2.DeploymentConfigV2",
        "components": [
          {
            "name": "token",
            "type": "tuple",
            "internalType": "struct IArtCoinsFactoryV2.TokenConfigV2",
            "components": [
              {
                "name": "tokenAdmin",
                "type": "address",
                "internalType": "address"
              },
              {
                "name": "name",
                "type": "string",
                "internalType": "string"
              },
              {
                "name": "symbol",
                "type": "string",
                "internalType": "string"
              },
              {
                "name": "salt",
                "type": "bytes32",
                "internalType": "bytes32"
              },
              {
                "name": "image",
                "type": "string",
                "internalType": "string"
              },
              {
                "name": "description",
                "type": "string",
                "internalType": "string"
              },
              {
                "name": "totalSupply",
                "type": "uint256",
                "internalType": "uint256"
              },
              {
                "name": "renderer",
                "type": "address",
                "internalType": "address"
              }
            ]
          },
          {
            "name": "pool",
            "type": "tuple",
            "internalType": "struct IArtCoinsFactoryV2.PoolConfigV2",
            "components": [
              {
                "name": "hook",
                "type": "address",
                "internalType": "address"
              },
              {
                "name": "tickIfToken0IsCoin",
                "type": "int24",
                "internalType": "int24"
              },
              {
                "name": "tickSpacing",
                "type": "int24",
                "internalType": "int24"
              },
              {
                "name": "extension",
                "type": "address",
                "internalType": "address"
              },
              {
                "name": "extensionData",
                "type": "bytes",
                "internalType": "bytes"
              }
            ]
          },
          {
            "name": "fee",
            "type": "tuple",
            "internalType": "struct IArtCoinsFactoryV2.FeeConfigV2",
            "components": [
              {
                "name": "lpFeePips",
                "type": "uint24",
                "internalType": "uint24"
              },
              {
                "name": "baselineSkimBps",
                "type": "uint24",
                "internalType": "uint24"
              },
              {
                "name": "bountyBps",
                "type": "uint16",
                "internalType": "uint16"
              },
              {
                "name": "maxReferralBpsOfVolume",
                "type": "uint24",
                "internalType": "uint24"
              },
              {
                "name": "bountyRecipient",
                "type": "address",
                "internalType": "address payable"
              }
            ]
          },
          {
            "name": "locker",
            "type": "tuple",
            "internalType": "struct IArtCoinsFactoryV2.LockerConfigV2",
            "components": [
              {
                "name": "locker",
                "type": "address",
                "internalType": "address"
              },
              {
                "name": "rewardRecipients",
                "type": "address[]",
                "internalType": "address[]"
              },
              {
                "name": "rewardBps",
                "type": "uint16[]",
                "internalType": "uint16[]"
              },
              {
                "name": "tickLower",
                "type": "int24[]",
                "internalType": "int24[]"
              },
              {
                "name": "tickUpper",
                "type": "int24[]",
                "internalType": "int24[]"
              },
              {
                "name": "positionBps",
                "type": "uint16[]",
                "internalType": "uint16[]"
              }
            ]
          },
          {
            "name": "mev",
            "type": "tuple",
            "internalType": "struct IArtCoinsFactoryV2.MevConfigV2",
            "components": [
              {
                "name": "module",
                "type": "address",
                "internalType": "address"
              },
              {
                "name": "startingSkimBps",
                "type": "uint24",
                "internalType": "uint24"
              },
              {
                "name": "windowSeconds",
                "type": "uint32",
                "internalType": "uint32"
              }
            ]
          },
          {
            "name": "restriction",
            "type": "tuple",
            "internalType": "struct IArtCoinsFactoryV2.RestrictionConfigV2",
            "components": [
              {
                "name": "restricted",
                "type": "bool",
                "internalType": "bool"
              },
              {
                "name": "allowed",
                "type": "address[]",
                "internalType": "address[]"
              }
            ]
          },
          {
            "name": "extensions",
            "type": "tuple[]",
            "internalType": "struct IArtCoinsFactoryV2.ExtensionConfigV2[]",
            "components": [
              {
                "name": "extension",
                "type": "address",
                "internalType": "address"
              },
              {
                "name": "msgValue",
                "type": "uint256",
                "internalType": "uint256"
              },
              {
                "name": "extensionBps",
                "type": "uint16",
                "internalType": "uint16"
              },
              {
                "name": "extensionData",
                "type": "bytes",
                "internalType": "bytes"
              }
            ]
          }
        ]
      },
      {
        "name": "poolKey",
        "type": "tuple",
        "internalType": "struct PoolKey",
        "components": [
          {
            "name": "currency0",
            "type": "address",
            "internalType": "Currency"
          },
          {
            "name": "currency1",
            "type": "address",
            "internalType": "Currency"
          },
          {
            "name": "fee",
            "type": "uint24",
            "internalType": "uint24"
          },
          {
            "name": "tickSpacing",
            "type": "int24",
            "internalType": "int24"
          },
          {
            "name": "hooks",
            "type": "address",
            "internalType": "contract IHooks"
          }
        ]
      },
      {
        "name": "token",
        "type": "address",
        "internalType": "address"
      },
      {
        "name": "extensionSupply",
        "type": "uint256",
        "internalType": "uint256"
      },
      {
        "name": "extensionIndex",
        "type": "uint256",
        "internalType": "uint256"
      }
    ],
    "outputs": [],
    "stateMutability": "payable"
  },
  {
    "type": "function",
    "name": "supportsInterface",
    "inputs": [
      {
        "name": "interfaceId",
        "type": "bytes4",
        "internalType": "bytes4"
      }
    ],
    "outputs": [
      {
        "name": "",
        "type": "bool",
        "internalType": "bool"
      }
    ],
    "stateMutability": "view"
  },
  {
    "type": "function",
    "name": "sweep",
    "inputs": [
      {
        "name": "token",
        "type": "address",
        "internalType": "address"
      },
      {
        "name": "index",
        "type": "uint256",
        "internalType": "uint256"
      }
    ],
    "outputs": [],
    "stateMutability": "nonpayable"
  },
  {
    "type": "function",
    "name": "tranche",
    "inputs": [
      {
        "name": "token",
        "type": "address",
        "internalType": "address"
      },
      {
        "name": "index",
        "type": "uint256",
        "internalType": "uint256"
      }
    ],
    "outputs": [
      {
        "name": "",
        "type": "tuple",
        "internalType": "struct IArtCoinsAirdropV2.Tranche",
        "components": [
          {
            "name": "sweepRecipient",
            "type": "address",
            "internalType": "address"
          },
          {
            "name": "merkleRoot",
            "type": "bytes32",
            "internalType": "bytes32"
          },
          {
            "name": "supply",
            "type": "uint256",
            "internalType": "uint256"
          },
          {
            "name": "totalClaimed",
            "type": "uint256",
            "internalType": "uint256"
          },
          {
            "name": "lockupEnd",
            "type": "uint256",
            "internalType": "uint256"
          },
          {
            "name": "vestingEnd",
            "type": "uint256",
            "internalType": "uint256"
          },
          {
            "name": "sweepTime",
            "type": "uint256",
            "internalType": "uint256"
          },
          {
            "name": "swept",
            "type": "bool",
            "internalType": "bool"
          }
        ]
      }
    ],
    "stateMutability": "view"
  },
  {
    "type": "event",
    "name": "AirdropClaimed",
    "inputs": [
      {
        "name": "token",
        "type": "address",
        "indexed": true,
        "internalType": "address"
      },
      {
        "name": "index",
        "type": "uint256",
        "indexed": true,
        "internalType": "uint256"
      },
      {
        "name": "recipient",
        "type": "address",
        "indexed": true,
        "internalType": "address"
      },
      {
        "name": "amount",
        "type": "uint256",
        "indexed": false,
        "internalType": "uint256"
      },
      {
        "name": "leafClaimed",
        "type": "uint256",
        "indexed": false,
        "internalType": "uint256"
      },
      {
        "name": "allocatedAmount",
        "type": "uint256",
        "indexed": false,
        "internalType": "uint256"
      }
    ],
    "anonymous": false
  },
  {
    "type": "event",
    "name": "AirdropCreated",
    "inputs": [
      {
        "name": "token",
        "type": "address",
        "indexed": true,
        "internalType": "address"
      },
      {
        "name": "index",
        "type": "uint256",
        "indexed": true,
        "internalType": "uint256"
      },
      {
        "name": "sweepRecipient",
        "type": "address",
        "indexed": true,
        "internalType": "address"
      },
      {
        "name": "merkleRoot",
        "type": "bytes32",
        "indexed": false,
        "internalType": "bytes32"
      },
      {
        "name": "supply",
        "type": "uint256",
        "indexed": false,
        "internalType": "uint256"
      },
      {
        "name": "lockupEnd",
        "type": "uint256",
        "indexed": false,
        "internalType": "uint256"
      },
      {
        "name": "vestingEnd",
        "type": "uint256",
        "indexed": false,
        "internalType": "uint256"
      },
      {
        "name": "sweepTime",
        "type": "uint256",
        "indexed": false,
        "internalType": "uint256"
      }
    ],
    "anonymous": false
  },
  {
    "type": "event",
    "name": "AirdropSwept",
    "inputs": [
      {
        "name": "token",
        "type": "address",
        "indexed": true,
        "internalType": "address"
      },
      {
        "name": "index",
        "type": "uint256",
        "indexed": true,
        "internalType": "uint256"
      },
      {
        "name": "recipient",
        "type": "address",
        "indexed": true,
        "internalType": "address"
      },
      {
        "name": "amount",
        "type": "uint256",
        "indexed": false,
        "internalType": "uint256"
      }
    ],
    "anonymous": false
  },
  {
    "type": "error",
    "name": "AirdropAlreadyExists",
    "inputs": []
  },
  {
    "type": "error",
    "name": "AirdropNotCreated",
    "inputs": []
  },
  {
    "type": "error",
    "name": "AirdropNotUnlocked",
    "inputs": []
  },
  {
    "type": "error",
    "name": "AlreadySwept",
    "inputs": []
  },
  {
    "type": "error",
    "name": "ClaimWindowClosed",
    "inputs": []
  },
  {
    "type": "error",
    "name": "ConstantsMismatch",
    "inputs": [
      {
        "name": "module",
        "type": "address",
        "internalType": "address"
      }
    ]
  },
  {
    "type": "error",
    "name": "DurationTooLong",
    "inputs": []
  },
  {
    "type": "error",
    "name": "InvalidAirdropBps",
    "inputs": []
  },
  {
    "type": "error",
    "name": "InvalidExtensionData",
    "inputs": []
  },
  {
    "type": "error",
    "name": "InvalidMerkleRoot",
    "inputs": []
  },
  {
    "type": "error",
    "name": "InvalidMsgValue",
    "inputs": []
  },
  {
    "type": "error",
    "name": "InvalidProof",
    "inputs": []
  },
  {
    "type": "error",
    "name": "SweepNotReady",
    "inputs": []
  },
  {
    "type": "error",
    "name": "TotalMaxClaimed",
    "inputs": []
  },
  {
    "type": "error",
    "name": "Unauthorized",
    "inputs": []
  },
  {
    "type": "error",
    "name": "UserMaxClaimed",
    "inputs": []
  },
  {
    "type": "error",
    "name": "WrongExtensionEntry",
    "inputs": []
  },
  {
    "type": "error",
    "name": "ZeroAddress",
    "inputs": []
  },
  {
    "type": "error",
    "name": "ZeroClaim",
    "inputs": []
  },
  {
    "type": "error",
    "name": "ZeroExtensionSupply",
    "inputs": []
  },
  {
    "type": "error",
    "name": "ZeroSweepRecipient",
    "inputs": []
  },
  {
    "type": "error",
    "name": "ZeroToClaim",
    "inputs": []
  }
] as const;
