// generated by ui/scripts/gen-abis.mjs from IArtCoinsFactoryV2.sol/IArtCoinsFactoryV2.json, do not edit.
// regenerate: forge build (repo root) then cd ui && npm run gen:abi
export const factoryV2Abi = [
  {
    "type": "function",
    "name": "STACK_VERSION",
    "inputs": [],
    "outputs": [
      {
        "name": "",
        "type": "uint16",
        "internalType": "uint16"
      }
    ],
    "stateMutability": "view"
  },
  {
    "type": "function",
    "name": "configHash",
    "inputs": [
      {
        "name": "c",
        "type": "tuple",
        "internalType": "struct IArtCoinsFactoryV2.DeploymentConfigV2",
        "components": [
          {
            "name": "token",
            "type": "tuple",
            "internalType": "struct IArtCoinsFactoryV2.TokenConfigV2",
            "components": [
              {
                "name": "tokenAdmin",
                "type": "address",
                "internalType": "address"
              },
              {
                "name": "name",
                "type": "string",
                "internalType": "string"
              },
              {
                "name": "symbol",
                "type": "string",
                "internalType": "string"
              },
              {
                "name": "salt",
                "type": "bytes32",
                "internalType": "bytes32"
              },
              {
                "name": "image",
                "type": "string",
                "internalType": "string"
              },
              {
                "name": "metadata",
                "type": "string",
                "internalType": "string"
              },
              {
                "name": "context",
                "type": "string",
                "internalType": "string"
              },
              {
                "name": "totalSupply",
                "type": "uint256",
                "internalType": "uint256"
              },
              {
                "name": "renderer",
                "type": "address",
                "internalType": "address"
              }
            ]
          },
          {
            "name": "pool",
            "type": "tuple",
            "internalType": "struct IArtCoinsFactoryV2.PoolConfigV2",
            "components": [
              {
                "name": "hook",
                "type": "address",
                "internalType": "address"
              },
              {
                "name": "tickIfToken0IsArtCoin",
                "type": "int24",
                "internalType": "int24"
              },
              {
                "name": "tickSpacing",
                "type": "int24",
                "internalType": "int24"
              },
              {
                "name": "extension",
                "type": "address",
                "internalType": "address"
              },
              {
                "name": "extensionData",
                "type": "bytes",
                "internalType": "bytes"
              }
            ]
          },
          {
            "name": "fee",
            "type": "tuple",
            "internalType": "struct IArtCoinsFactoryV2.FeeConfigV2",
            "components": [
              {
                "name": "lpFee",
                "type": "uint24",
                "internalType": "uint24"
              },
              {
                "name": "baselineSkimBps",
                "type": "uint24",
                "internalType": "uint24"
              },
              {
                "name": "bountyBps",
                "type": "uint16",
                "internalType": "uint16"
              },
              {
                "name": "maxReferralBpsOfVolume",
                "type": "uint24",
                "internalType": "uint24"
              },
              {
                "name": "bountyRecipient",
                "type": "address",
                "internalType": "address payable"
              }
            ]
          },
          {
            "name": "locker",
            "type": "tuple",
            "internalType": "struct IArtCoinsFactoryV2.LockerConfigV2",
            "components": [
              {
                "name": "locker",
                "type": "address",
                "internalType": "address"
              },
              {
                "name": "rewardRecipients",
                "type": "address[]",
                "internalType": "address[]"
              },
              {
                "name": "rewardBps",
                "type": "uint16[]",
                "internalType": "uint16[]"
              },
              {
                "name": "tickLower",
                "type": "int24[]",
                "internalType": "int24[]"
              },
              {
                "name": "tickUpper",
                "type": "int24[]",
                "internalType": "int24[]"
              },
              {
                "name": "positionBps",
                "type": "uint16[]",
                "internalType": "uint16[]"
              }
            ]
          },
          {
            "name": "mev",
            "type": "tuple",
            "internalType": "struct IArtCoinsFactoryV2.MevConfigV2",
            "components": [
              {
                "name": "module",
                "type": "address",
                "internalType": "address"
              },
              {
                "name": "startingSkimBps",
                "type": "uint24",
                "internalType": "uint24"
              },
              {
                "name": "windowSeconds",
                "type": "uint32",
                "internalType": "uint32"
              }
            ]
          },
          {
            "name": "tax",
            "type": "tuple",
            "internalType": "struct IArtCoinsFactoryV2.TaxConfigV2",
            "components": [
              {
                "name": "mode",
                "type": "uint8",
                "internalType": "uint8"
              },
              {
                "name": "taxBps",
                "type": "uint16",
                "internalType": "uint16"
              },
              {
                "name": "taxBpsMax",
                "type": "uint16",
                "internalType": "uint16"
              },
              {
                "name": "taxSink",
                "type": "address",
                "internalType": "address"
              },
              {
                "name": "venueAdmin",
                "type": "address",
                "internalType": "address"
              },
              {
                "name": "exempt",
                "type": "address[]",
                "internalType": "address[]"
              },
              {
                "name": "venues",
                "type": "tuple[]",
                "internalType": "struct IArtCoinsFactoryV2.TaxVenue[]",
                "components": [
                  {
                    "name": "kind",
                    "type": "uint8",
                    "internalType": "uint8"
                  },
                  {
                    "name": "factory",
                    "type": "address",
                    "internalType": "address"
                  },
                  {
                    "name": "initCodeHash",
                    "type": "bytes32",
                    "internalType": "bytes32"
                  },
                  {
                    "name": "counterToken",
                    "type": "address",
                    "internalType": "address"
                  },
                  {
                    "name": "v3Fee",
                    "type": "uint24",
                    "internalType": "uint24"
                  }
                ]
              }
            ]
          },
          {
            "name": "extensions",
            "type": "tuple[]",
            "internalType": "struct IArtCoinsFactoryV2.ExtensionConfigV2[]",
            "components": [
              {
                "name": "extension",
                "type": "address",
                "internalType": "address"
              },
              {
                "name": "msgValue",
                "type": "uint256",
                "internalType": "uint256"
              },
              {
                "name": "extensionBps",
                "type": "uint16",
                "internalType": "uint16"
              },
              {
                "name": "extensionData",
                "type": "bytes",
                "internalType": "bytes"
              }
            ]
          }
        ]
      }
    ],
    "outputs": [
      {
        "name": "",
        "type": "bytes32",
        "internalType": "bytes32"
      }
    ],
    "stateMutability": "pure"
  },
  {
    "type": "function",
    "name": "constantsHash",
    "inputs": [],
    "outputs": [
      {
        "name": "",
        "type": "bytes32",
        "internalType": "bytes32"
      }
    ],
    "stateMutability": "pure"
  },
  {
    "type": "function",
    "name": "defaultProtocolFeeBps",
    "inputs": [],
    "outputs": [
      {
        "name": "",
        "type": "uint16",
        "internalType": "uint16"
      }
    ],
    "stateMutability": "view"
  },
  {
    "type": "function",
    "name": "deployFee",
    "inputs": [],
    "outputs": [
      {
        "name": "",
        "type": "uint256",
        "internalType": "uint256"
      }
    ],
    "stateMutability": "view"
  },
  {
    "type": "function",
    "name": "deployToken",
    "inputs": [
      {
        "name": "c",
        "type": "tuple",
        "internalType": "struct IArtCoinsFactoryV2.DeploymentConfigV2",
        "components": [
          {
            "name": "token",
            "type": "tuple",
            "internalType": "struct IArtCoinsFactoryV2.TokenConfigV2",
            "components": [
              {
                "name": "tokenAdmin",
                "type": "address",
                "internalType": "address"
              },
              {
                "name": "name",
                "type": "string",
                "internalType": "string"
              },
              {
                "name": "symbol",
                "type": "string",
                "internalType": "string"
              },
              {
                "name": "salt",
                "type": "bytes32",
                "internalType": "bytes32"
              },
              {
                "name": "image",
                "type": "string",
                "internalType": "string"
              },
              {
                "name": "metadata",
                "type": "string",
                "internalType": "string"
              },
              {
                "name": "context",
                "type": "string",
                "internalType": "string"
              },
              {
                "name": "totalSupply",
                "type": "uint256",
                "internalType": "uint256"
              },
              {
                "name": "renderer",
                "type": "address",
                "internalType": "address"
              }
            ]
          },
          {
            "name": "pool",
            "type": "tuple",
            "internalType": "struct IArtCoinsFactoryV2.PoolConfigV2",
            "components": [
              {
                "name": "hook",
                "type": "address",
                "internalType": "address"
              },
              {
                "name": "tickIfToken0IsArtCoin",
                "type": "int24",
                "internalType": "int24"
              },
              {
                "name": "tickSpacing",
                "type": "int24",
                "internalType": "int24"
              },
              {
                "name": "extension",
                "type": "address",
                "internalType": "address"
              },
              {
                "name": "extensionData",
                "type": "bytes",
                "internalType": "bytes"
              }
            ]
          },
          {
            "name": "fee",
            "type": "tuple",
            "internalType": "struct IArtCoinsFactoryV2.FeeConfigV2",
            "components": [
              {
                "name": "lpFee",
                "type": "uint24",
                "internalType": "uint24"
              },
              {
                "name": "baselineSkimBps",
                "type": "uint24",
                "internalType": "uint24"
              },
              {
                "name": "bountyBps",
                "type": "uint16",
                "internalType": "uint16"
              },
              {
                "name": "maxReferralBpsOfVolume",
                "type": "uint24",
                "internalType": "uint24"
              },
              {
                "name": "bountyRecipient",
                "type": "address",
                "internalType": "address payable"
              }
            ]
          },
          {
            "name": "locker",
            "type": "tuple",
            "internalType": "struct IArtCoinsFactoryV2.LockerConfigV2",
            "components": [
              {
                "name": "locker",
                "type": "address",
                "internalType": "address"
              },
              {
                "name": "rewardRecipients",
                "type": "address[]",
                "internalType": "address[]"
              },
              {
                "name": "rewardBps",
                "type": "uint16[]",
                "internalType": "uint16[]"
              },
              {
                "name": "tickLower",
                "type": "int24[]",
                "internalType": "int24[]"
              },
              {
                "name": "tickUpper",
                "type": "int24[]",
                "internalType": "int24[]"
              },
              {
                "name": "positionBps",
                "type": "uint16[]",
                "internalType": "uint16[]"
              }
            ]
          },
          {
            "name": "mev",
            "type": "tuple",
            "internalType": "struct IArtCoinsFactoryV2.MevConfigV2",
            "components": [
              {
                "name": "module",
                "type": "address",
                "internalType": "address"
              },
              {
                "name": "startingSkimBps",
                "type": "uint24",
                "internalType": "uint24"
              },
              {
                "name": "windowSeconds",
                "type": "uint32",
                "internalType": "uint32"
              }
            ]
          },
          {
            "name": "tax",
            "type": "tuple",
            "internalType": "struct IArtCoinsFactoryV2.TaxConfigV2",
            "components": [
              {
                "name": "mode",
                "type": "uint8",
                "internalType": "uint8"
              },
              {
                "name": "taxBps",
                "type": "uint16",
                "internalType": "uint16"
              },
              {
                "name": "taxBpsMax",
                "type": "uint16",
                "internalType": "uint16"
              },
              {
                "name": "taxSink",
                "type": "address",
                "internalType": "address"
              },
              {
                "name": "venueAdmin",
                "type": "address",
                "internalType": "address"
              },
              {
                "name": "exempt",
                "type": "address[]",
                "internalType": "address[]"
              },
              {
                "name": "venues",
                "type": "tuple[]",
                "internalType": "struct IArtCoinsFactoryV2.TaxVenue[]",
                "components": [
                  {
                    "name": "kind",
                    "type": "uint8",
                    "internalType": "uint8"
                  },
                  {
                    "name": "factory",
                    "type": "address",
                    "internalType": "address"
                  },
                  {
                    "name": "initCodeHash",
                    "type": "bytes32",
                    "internalType": "bytes32"
                  },
                  {
                    "name": "counterToken",
                    "type": "address",
                    "internalType": "address"
                  },
                  {
                    "name": "v3Fee",
                    "type": "uint24",
                    "internalType": "uint24"
                  }
                ]
              }
            ]
          },
          {
            "name": "extensions",
            "type": "tuple[]",
            "internalType": "struct IArtCoinsFactoryV2.ExtensionConfigV2[]",
            "components": [
              {
                "name": "extension",
                "type": "address",
                "internalType": "address"
              },
              {
                "name": "msgValue",
                "type": "uint256",
                "internalType": "uint256"
              },
              {
                "name": "extensionBps",
                "type": "uint16",
                "internalType": "uint16"
              },
              {
                "name": "extensionData",
                "type": "bytes",
                "internalType": "bytes"
              }
            ]
          }
        ]
      }
    ],
    "outputs": [
      {
        "name": "token",
        "type": "address",
        "internalType": "address"
      }
    ],
    "stateMutability": "payable"
  },
  {
    "type": "function",
    "name": "deployTokenAsOwner",
    "inputs": [
      {
        "name": "c",
        "type": "tuple",
        "internalType": "struct IArtCoinsFactoryV2.DeploymentConfigV2",
        "components": [
          {
            "name": "token",
            "type": "tuple",
            "internalType": "struct IArtCoinsFactoryV2.TokenConfigV2",
            "components": [
              {
                "name": "tokenAdmin",
                "type": "address",
                "internalType": "address"
              },
              {
                "name": "name",
                "type": "string",
                "internalType": "string"
              },
              {
                "name": "symbol",
                "type": "string",
                "internalType": "string"
              },
              {
                "name": "salt",
                "type": "bytes32",
                "internalType": "bytes32"
              },
              {
                "name": "image",
                "type": "string",
                "internalType": "string"
              },
              {
                "name": "metadata",
                "type": "string",
                "internalType": "string"
              },
              {
                "name": "context",
                "type": "string",
                "internalType": "string"
              },
              {
                "name": "totalSupply",
                "type": "uint256",
                "internalType": "uint256"
              },
              {
                "name": "renderer",
                "type": "address",
                "internalType": "address"
              }
            ]
          },
          {
            "name": "pool",
            "type": "tuple",
            "internalType": "struct IArtCoinsFactoryV2.PoolConfigV2",
            "components": [
              {
                "name": "hook",
                "type": "address",
                "internalType": "address"
              },
              {
                "name": "tickIfToken0IsArtCoin",
                "type": "int24",
                "internalType": "int24"
              },
              {
                "name": "tickSpacing",
                "type": "int24",
                "internalType": "int24"
              },
              {
                "name": "extension",
                "type": "address",
                "internalType": "address"
              },
              {
                "name": "extensionData",
                "type": "bytes",
                "internalType": "bytes"
              }
            ]
          },
          {
            "name": "fee",
            "type": "tuple",
            "internalType": "struct IArtCoinsFactoryV2.FeeConfigV2",
            "components": [
              {
                "name": "lpFee",
                "type": "uint24",
                "internalType": "uint24"
              },
              {
                "name": "baselineSkimBps",
                "type": "uint24",
                "internalType": "uint24"
              },
              {
                "name": "bountyBps",
                "type": "uint16",
                "internalType": "uint16"
              },
              {
                "name": "maxReferralBpsOfVolume",
                "type": "uint24",
                "internalType": "uint24"
              },
              {
                "name": "bountyRecipient",
                "type": "address",
                "internalType": "address payable"
              }
            ]
          },
          {
            "name": "locker",
            "type": "tuple",
            "internalType": "struct IArtCoinsFactoryV2.LockerConfigV2",
            "components": [
              {
                "name": "locker",
                "type": "address",
                "internalType": "address"
              },
              {
                "name": "rewardRecipients",
                "type": "address[]",
                "internalType": "address[]"
              },
              {
                "name": "rewardBps",
                "type": "uint16[]",
                "internalType": "uint16[]"
              },
              {
                "name": "tickLower",
                "type": "int24[]",
                "internalType": "int24[]"
              },
              {
                "name": "tickUpper",
                "type": "int24[]",
                "internalType": "int24[]"
              },
              {
                "name": "positionBps",
                "type": "uint16[]",
                "internalType": "uint16[]"
              }
            ]
          },
          {
            "name": "mev",
            "type": "tuple",
            "internalType": "struct IArtCoinsFactoryV2.MevConfigV2",
            "components": [
              {
                "name": "module",
                "type": "address",
                "internalType": "address"
              },
              {
                "name": "startingSkimBps",
                "type": "uint24",
                "internalType": "uint24"
              },
              {
                "name": "windowSeconds",
                "type": "uint32",
                "internalType": "uint32"
              }
            ]
          },
          {
            "name": "tax",
            "type": "tuple",
            "internalType": "struct IArtCoinsFactoryV2.TaxConfigV2",
            "components": [
              {
                "name": "mode",
                "type": "uint8",
                "internalType": "uint8"
              },
              {
                "name": "taxBps",
                "type": "uint16",
                "internalType": "uint16"
              },
              {
                "name": "taxBpsMax",
                "type": "uint16",
                "internalType": "uint16"
              },
              {
                "name": "taxSink",
                "type": "address",
                "internalType": "address"
              },
              {
                "name": "venueAdmin",
                "type": "address",
                "internalType": "address"
              },
              {
                "name": "exempt",
                "type": "address[]",
                "internalType": "address[]"
              },
              {
                "name": "venues",
                "type": "tuple[]",
                "internalType": "struct IArtCoinsFactoryV2.TaxVenue[]",
                "components": [
                  {
                    "name": "kind",
                    "type": "uint8",
                    "internalType": "uint8"
                  },
                  {
                    "name": "factory",
                    "type": "address",
                    "internalType": "address"
                  },
                  {
                    "name": "initCodeHash",
                    "type": "bytes32",
                    "internalType": "bytes32"
                  },
                  {
                    "name": "counterToken",
                    "type": "address",
                    "internalType": "address"
                  },
                  {
                    "name": "v3Fee",
                    "type": "uint24",
                    "internalType": "uint24"
                  }
                ]
              }
            ]
          },
          {
            "name": "extensions",
            "type": "tuple[]",
            "internalType": "struct IArtCoinsFactoryV2.ExtensionConfigV2[]",
            "components": [
              {
                "name": "extension",
                "type": "address",
                "internalType": "address"
              },
              {
                "name": "msgValue",
                "type": "uint256",
                "internalType": "uint256"
              },
              {
                "name": "extensionBps",
                "type": "uint16",
                "internalType": "uint16"
              },
              {
                "name": "extensionData",
                "type": "bytes",
                "internalType": "bytes"
              }
            ]
          }
        ]
      },
      {
        "name": "protocolBps",
        "type": "uint16",
        "internalType": "uint16"
      }
    ],
    "outputs": [
      {
        "name": "token",
        "type": "address",
        "internalType": "address"
      }
    ],
    "stateMutability": "payable"
  },
  {
    "type": "function",
    "name": "deploymentInfo",
    "inputs": [
      {
        "name": "token",
        "type": "address",
        "internalType": "address"
      }
    ],
    "outputs": [
      {
        "name": "",
        "type": "tuple",
        "internalType": "struct IArtCoinsFactoryV2.DeploymentInfoV2",
        "components": [
          {
            "name": "token",
            "type": "address",
            "internalType": "address"
          },
          {
            "name": "hook",
            "type": "address",
            "internalType": "address"
          },
          {
            "name": "locker",
            "type": "address",
            "internalType": "address"
          },
          {
            "name": "mevModule",
            "type": "address",
            "internalType": "address"
          },
          {
            "name": "poolId",
            "type": "bytes32",
            "internalType": "PoolId"
          },
          {
            "name": "version",
            "type": "uint16",
            "internalType": "uint16"
          },
          {
            "name": "launchedAt",
            "type": "uint40",
            "internalType": "uint40"
          },
          {
            "name": "extensions",
            "type": "address[]",
            "internalType": "address[]"
          }
        ]
      }
    ],
    "stateMutability": "view"
  },
  {
    "type": "function",
    "name": "deprecated",
    "inputs": [],
    "outputs": [
      {
        "name": "",
        "type": "bool",
        "internalType": "bool"
      }
    ],
    "stateMutability": "view"
  },
  {
    "type": "function",
    "name": "enabledEscrows",
    "inputs": [
      {
        "name": "escrow",
        "type": "address",
        "internalType": "address"
      }
    ],
    "outputs": [
      {
        "name": "",
        "type": "bool",
        "internalType": "bool"
      }
    ],
    "stateMutability": "view"
  },
  {
    "type": "function",
    "name": "enabledExtensions",
    "inputs": [
      {
        "name": "extension",
        "type": "address",
        "internalType": "address"
      }
    ],
    "outputs": [
      {
        "name": "",
        "type": "bool",
        "internalType": "bool"
      }
    ],
    "stateMutability": "view"
  },
  {
    "type": "function",
    "name": "enabledHooks",
    "inputs": [
      {
        "name": "hook",
        "type": "address",
        "internalType": "address"
      }
    ],
    "outputs": [
      {
        "name": "",
        "type": "bool",
        "internalType": "bool"
      }
    ],
    "stateMutability": "view"
  },
  {
    "type": "function",
    "name": "enabledLockers",
    "inputs": [
      {
        "name": "locker",
        "type": "address",
        "internalType": "address"
      }
    ],
    "outputs": [
      {
        "name": "",
        "type": "bool",
        "internalType": "bool"
      }
    ],
    "stateMutability": "view"
  },
  {
    "type": "function",
    "name": "enabledMevModules",
    "inputs": [
      {
        "name": "module",
        "type": "address",
        "internalType": "address"
      }
    ],
    "outputs": [
      {
        "name": "",
        "type": "bool",
        "internalType": "bool"
      }
    ],
    "stateMutability": "view"
  },
  {
    "type": "function",
    "name": "isArtCoin",
    "inputs": [
      {
        "name": "token",
        "type": "address",
        "internalType": "address"
      }
    ],
    "outputs": [
      {
        "name": "",
        "type": "bool",
        "internalType": "bool"
      }
    ],
    "stateMutability": "view"
  },
  {
    "type": "function",
    "name": "minProtocolSkimShareBps",
    "inputs": [],
    "outputs": [
      {
        "name": "",
        "type": "uint16",
        "internalType": "uint16"
      }
    ],
    "stateMutability": "view"
  },
  {
    "type": "function",
    "name": "predictToken",
    "inputs": [
      {
        "name": "sender",
        "type": "address",
        "internalType": "address"
      },
      {
        "name": "c",
        "type": "tuple",
        "internalType": "struct IArtCoinsFactoryV2.DeploymentConfigV2",
        "components": [
          {
            "name": "token",
            "type": "tuple",
            "internalType": "struct IArtCoinsFactoryV2.TokenConfigV2",
            "components": [
              {
                "name": "tokenAdmin",
                "type": "address",
                "internalType": "address"
              },
              {
                "name": "name",
                "type": "string",
                "internalType": "string"
              },
              {
                "name": "symbol",
                "type": "string",
                "internalType": "string"
              },
              {
                "name": "salt",
                "type": "bytes32",
                "internalType": "bytes32"
              },
              {
                "name": "image",
                "type": "string",
                "internalType": "string"
              },
              {
                "name": "metadata",
                "type": "string",
                "internalType": "string"
              },
              {
                "name": "context",
                "type": "string",
                "internalType": "string"
              },
              {
                "name": "totalSupply",
                "type": "uint256",
                "internalType": "uint256"
              },
              {
                "name": "renderer",
                "type": "address",
                "internalType": "address"
              }
            ]
          },
          {
            "name": "pool",
            "type": "tuple",
            "internalType": "struct IArtCoinsFactoryV2.PoolConfigV2",
            "components": [
              {
                "name": "hook",
                "type": "address",
                "internalType": "address"
              },
              {
                "name": "tickIfToken0IsArtCoin",
                "type": "int24",
                "internalType": "int24"
              },
              {
                "name": "tickSpacing",
                "type": "int24",
                "internalType": "int24"
              },
              {
                "name": "extension",
                "type": "address",
                "internalType": "address"
              },
              {
                "name": "extensionData",
                "type": "bytes",
                "internalType": "bytes"
              }
            ]
          },
          {
            "name": "fee",
            "type": "tuple",
            "internalType": "struct IArtCoinsFactoryV2.FeeConfigV2",
            "components": [
              {
                "name": "lpFee",
                "type": "uint24",
                "internalType": "uint24"
              },
              {
                "name": "baselineSkimBps",
                "type": "uint24",
                "internalType": "uint24"
              },
              {
                "name": "bountyBps",
                "type": "uint16",
                "internalType": "uint16"
              },
              {
                "name": "maxReferralBpsOfVolume",
                "type": "uint24",
                "internalType": "uint24"
              },
              {
                "name": "bountyRecipient",
                "type": "address",
                "internalType": "address payable"
              }
            ]
          },
          {
            "name": "locker",
            "type": "tuple",
            "internalType": "struct IArtCoinsFactoryV2.LockerConfigV2",
            "components": [
              {
                "name": "locker",
                "type": "address",
                "internalType": "address"
              },
              {
                "name": "rewardRecipients",
                "type": "address[]",
                "internalType": "address[]"
              },
              {
                "name": "rewardBps",
                "type": "uint16[]",
                "internalType": "uint16[]"
              },
              {
                "name": "tickLower",
                "type": "int24[]",
                "internalType": "int24[]"
              },
              {
                "name": "tickUpper",
                "type": "int24[]",
                "internalType": "int24[]"
              },
              {
                "name": "positionBps",
                "type": "uint16[]",
                "internalType": "uint16[]"
              }
            ]
          },
          {
            "name": "mev",
            "type": "tuple",
            "internalType": "struct IArtCoinsFactoryV2.MevConfigV2",
            "components": [
              {
                "name": "module",
                "type": "address",
                "internalType": "address"
              },
              {
                "name": "startingSkimBps",
                "type": "uint24",
                "internalType": "uint24"
              },
              {
                "name": "windowSeconds",
                "type": "uint32",
                "internalType": "uint32"
              }
            ]
          },
          {
            "name": "tax",
            "type": "tuple",
            "internalType": "struct IArtCoinsFactoryV2.TaxConfigV2",
            "components": [
              {
                "name": "mode",
                "type": "uint8",
                "internalType": "uint8"
              },
              {
                "name": "taxBps",
                "type": "uint16",
                "internalType": "uint16"
              },
              {
                "name": "taxBpsMax",
                "type": "uint16",
                "internalType": "uint16"
              },
              {
                "name": "taxSink",
                "type": "address",
                "internalType": "address"
              },
              {
                "name": "venueAdmin",
                "type": "address",
                "internalType": "address"
              },
              {
                "name": "exempt",
                "type": "address[]",
                "internalType": "address[]"
              },
              {
                "name": "venues",
                "type": "tuple[]",
                "internalType": "struct IArtCoinsFactoryV2.TaxVenue[]",
                "components": [
                  {
                    "name": "kind",
                    "type": "uint8",
                    "internalType": "uint8"
                  },
                  {
                    "name": "factory",
                    "type": "address",
                    "internalType": "address"
                  },
                  {
                    "name": "initCodeHash",
                    "type": "bytes32",
                    "internalType": "bytes32"
                  },
                  {
                    "name": "counterToken",
                    "type": "address",
                    "internalType": "address"
                  },
                  {
                    "name": "v3Fee",
                    "type": "uint24",
                    "internalType": "uint24"
                  }
                ]
              }
            ]
          },
          {
            "name": "extensions",
            "type": "tuple[]",
            "internalType": "struct IArtCoinsFactoryV2.ExtensionConfigV2[]",
            "components": [
              {
                "name": "extension",
                "type": "address",
                "internalType": "address"
              },
              {
                "name": "msgValue",
                "type": "uint256",
                "internalType": "uint256"
              },
              {
                "name": "extensionBps",
                "type": "uint16",
                "internalType": "uint16"
              },
              {
                "name": "extensionData",
                "type": "bytes",
                "internalType": "bytes"
              }
            ]
          }
        ]
      }
    ],
    "outputs": [
      {
        "name": "",
        "type": "address",
        "internalType": "address"
      }
    ],
    "stateMutability": "view"
  },
  {
    "type": "function",
    "name": "protocolRecipient",
    "inputs": [],
    "outputs": [
      {
        "name": "",
        "type": "address",
        "internalType": "address payable"
      }
    ],
    "stateMutability": "view"
  },
  {
    "type": "function",
    "name": "referralPayout",
    "inputs": [],
    "outputs": [
      {
        "name": "",
        "type": "address",
        "internalType": "address payable"
      }
    ],
    "stateMutability": "view"
  },
  {
    "type": "function",
    "name": "rescue",
    "inputs": [
      {
        "name": "token",
        "type": "address",
        "internalType": "address"
      },
      {
        "name": "to",
        "type": "address",
        "internalType": "address"
      },
      {
        "name": "amount",
        "type": "uint256",
        "internalType": "uint256"
      }
    ],
    "outputs": [],
    "stateMutability": "nonpayable"
  },
  {
    "type": "function",
    "name": "setDefaultProtocolFeeBps",
    "inputs": [
      {
        "name": "bps",
        "type": "uint16",
        "internalType": "uint16"
      }
    ],
    "outputs": [],
    "stateMutability": "nonpayable"
  },
  {
    "type": "function",
    "name": "setDeployFee",
    "inputs": [
      {
        "name": "fee",
        "type": "uint256",
        "internalType": "uint256"
      }
    ],
    "outputs": [],
    "stateMutability": "nonpayable"
  },
  {
    "type": "function",
    "name": "setDeprecated",
    "inputs": [
      {
        "name": "deprecated_",
        "type": "bool",
        "internalType": "bool"
      }
    ],
    "outputs": [],
    "stateMutability": "nonpayable"
  },
  {
    "type": "function",
    "name": "setEscrow",
    "inputs": [
      {
        "name": "escrow",
        "type": "address",
        "internalType": "address"
      },
      {
        "name": "enabled",
        "type": "bool",
        "internalType": "bool"
      }
    ],
    "outputs": [],
    "stateMutability": "nonpayable"
  },
  {
    "type": "function",
    "name": "setExtension",
    "inputs": [
      {
        "name": "extension",
        "type": "address",
        "internalType": "address"
      },
      {
        "name": "enabled",
        "type": "bool",
        "internalType": "bool"
      }
    ],
    "outputs": [],
    "stateMutability": "nonpayable"
  },
  {
    "type": "function",
    "name": "setHook",
    "inputs": [
      {
        "name": "hook",
        "type": "address",
        "internalType": "address"
      },
      {
        "name": "enabled",
        "type": "bool",
        "internalType": "bool"
      }
    ],
    "outputs": [],
    "stateMutability": "nonpayable"
  },
  {
    "type": "function",
    "name": "setLocker",
    "inputs": [
      {
        "name": "locker",
        "type": "address",
        "internalType": "address"
      },
      {
        "name": "enabled",
        "type": "bool",
        "internalType": "bool"
      }
    ],
    "outputs": [],
    "stateMutability": "nonpayable"
  },
  {
    "type": "function",
    "name": "setMevModule",
    "inputs": [
      {
        "name": "module",
        "type": "address",
        "internalType": "address"
      },
      {
        "name": "enabled",
        "type": "bool",
        "internalType": "bool"
      }
    ],
    "outputs": [],
    "stateMutability": "nonpayable"
  },
  {
    "type": "function",
    "name": "setMinProtocolSkimShareBps",
    "inputs": [
      {
        "name": "bps",
        "type": "uint16",
        "internalType": "uint16"
      }
    ],
    "outputs": [],
    "stateMutability": "nonpayable"
  },
  {
    "type": "function",
    "name": "setProtocolRecipient",
    "inputs": [
      {
        "name": "recipient",
        "type": "address",
        "internalType": "address payable"
      }
    ],
    "outputs": [],
    "stateMutability": "nonpayable"
  },
  {
    "type": "function",
    "name": "setReferralPayout",
    "inputs": [
      {
        "name": "payout",
        "type": "address",
        "internalType": "address payable"
      }
    ],
    "outputs": [],
    "stateMutability": "nonpayable"
  },
  {
    "type": "function",
    "name": "setTeamFeeRecipient",
    "inputs": [
      {
        "name": "recipient",
        "type": "address",
        "internalType": "address"
      }
    ],
    "outputs": [],
    "stateMutability": "nonpayable"
  },
  {
    "type": "function",
    "name": "teamFeeRecipient",
    "inputs": [],
    "outputs": [
      {
        "name": "",
        "type": "address",
        "internalType": "address"
      }
    ],
    "stateMutability": "view"
  },
  {
    "type": "event",
    "name": "DefaultProtocolFeeBpsSet",
    "inputs": [
      {
        "name": "oldBps",
        "type": "uint16",
        "indexed": false,
        "internalType": "uint16"
      },
      {
        "name": "newBps",
        "type": "uint16",
        "indexed": false,
        "internalType": "uint16"
      }
    ],
    "anonymous": false
  },
  {
    "type": "event",
    "name": "DeployFeePaid",
    "inputs": [
      {
        "name": "recipient",
        "type": "address",
        "indexed": true,
        "internalType": "address"
      },
      {
        "name": "amount",
        "type": "uint256",
        "indexed": false,
        "internalType": "uint256"
      }
    ],
    "anonymous": false
  },
  {
    "type": "event",
    "name": "DeployFeeSet",
    "inputs": [
      {
        "name": "oldFee",
        "type": "uint256",
        "indexed": false,
        "internalType": "uint256"
      },
      {
        "name": "newFee",
        "type": "uint256",
        "indexed": false,
        "internalType": "uint256"
      }
    ],
    "anonymous": false
  },
  {
    "type": "event",
    "name": "DeprecatedSet",
    "inputs": [
      {
        "name": "deprecated",
        "type": "bool",
        "indexed": false,
        "internalType": "bool"
      }
    ],
    "anonymous": false
  },
  {
    "type": "event",
    "name": "EscrowSet",
    "inputs": [
      {
        "name": "escrow",
        "type": "address",
        "indexed": true,
        "internalType": "address"
      },
      {
        "name": "enabled",
        "type": "bool",
        "indexed": false,
        "internalType": "bool"
      }
    ],
    "anonymous": false
  },
  {
    "type": "event",
    "name": "ExtensionSet",
    "inputs": [
      {
        "name": "extension",
        "type": "address",
        "indexed": true,
        "internalType": "address"
      },
      {
        "name": "enabled",
        "type": "bool",
        "indexed": false,
        "internalType": "bool"
      }
    ],
    "anonymous": false
  },
  {
    "type": "event",
    "name": "ExtensionTriggered",
    "inputs": [
      {
        "name": "token",
        "type": "address",
        "indexed": true,
        "internalType": "address"
      },
      {
        "name": "extension",
        "type": "address",
        "indexed": true,
        "internalType": "address"
      },
      {
        "name": "extensionSupply",
        "type": "uint256",
        "indexed": false,
        "internalType": "uint256"
      },
      {
        "name": "msgValue",
        "type": "uint256",
        "indexed": false,
        "internalType": "uint256"
      }
    ],
    "anonymous": false
  },
  {
    "type": "event",
    "name": "HookSet",
    "inputs": [
      {
        "name": "hook",
        "type": "address",
        "indexed": true,
        "internalType": "address"
      },
      {
        "name": "enabled",
        "type": "bool",
        "indexed": false,
        "internalType": "bool"
      }
    ],
    "anonymous": false
  },
  {
    "type": "event",
    "name": "LockerSet",
    "inputs": [
      {
        "name": "locker",
        "type": "address",
        "indexed": true,
        "internalType": "address"
      },
      {
        "name": "enabled",
        "type": "bool",
        "indexed": false,
        "internalType": "bool"
      }
    ],
    "anonymous": false
  },
  {
    "type": "event",
    "name": "MevModuleSet",
    "inputs": [
      {
        "name": "module",
        "type": "address",
        "indexed": true,
        "internalType": "address"
      },
      {
        "name": "enabled",
        "type": "bool",
        "indexed": false,
        "internalType": "bool"
      }
    ],
    "anonymous": false
  },
  {
    "type": "event",
    "name": "MinProtocolSkimShareBpsSet",
    "inputs": [
      {
        "name": "oldBps",
        "type": "uint16",
        "indexed": false,
        "internalType": "uint16"
      },
      {
        "name": "newBps",
        "type": "uint16",
        "indexed": false,
        "internalType": "uint16"
      }
    ],
    "anonymous": false
  },
  {
    "type": "event",
    "name": "ProtocolRecipientSet",
    "inputs": [
      {
        "name": "oldRecipient",
        "type": "address",
        "indexed": true,
        "internalType": "address"
      },
      {
        "name": "newRecipient",
        "type": "address",
        "indexed": true,
        "internalType": "address"
      }
    ],
    "anonymous": false
  },
  {
    "type": "event",
    "name": "ReferralPayoutSet",
    "inputs": [
      {
        "name": "oldPayout",
        "type": "address",
        "indexed": true,
        "internalType": "address"
      },
      {
        "name": "newPayout",
        "type": "address",
        "indexed": true,
        "internalType": "address"
      }
    ],
    "anonymous": false
  },
  {
    "type": "event",
    "name": "Rescued",
    "inputs": [
      {
        "name": "token",
        "type": "address",
        "indexed": true,
        "internalType": "address"
      },
      {
        "name": "to",
        "type": "address",
        "indexed": true,
        "internalType": "address"
      },
      {
        "name": "amount",
        "type": "uint256",
        "indexed": false,
        "internalType": "uint256"
      }
    ],
    "anonymous": false
  },
  {
    "type": "event",
    "name": "TeamFeeRecipientSet",
    "inputs": [
      {
        "name": "oldRecipient",
        "type": "address",
        "indexed": true,
        "internalType": "address"
      },
      {
        "name": "newRecipient",
        "type": "address",
        "indexed": true,
        "internalType": "address"
      }
    ],
    "anonymous": false
  },
  {
    "type": "event",
    "name": "TokenCreatedV2",
    "inputs": [
      {
        "name": "sender",
        "type": "address",
        "indexed": true,
        "internalType": "address"
      },
      {
        "name": "token",
        "type": "address",
        "indexed": true,
        "internalType": "address"
      },
      {
        "name": "poolId",
        "type": "bytes32",
        "indexed": true,
        "internalType": "PoolId"
      },
      {
        "name": "stackVersion",
        "type": "uint16",
        "indexed": false,
        "internalType": "uint16"
      },
      {
        "name": "configHash",
        "type": "bytes32",
        "indexed": false,
        "internalType": "bytes32"
      },
      {
        "name": "protocolRecipient",
        "type": "address",
        "indexed": false,
        "internalType": "address"
      },
      {
        "name": "referralPayout",
        "type": "address",
        "indexed": false,
        "internalType": "address"
      },
      {
        "name": "protocolBps",
        "type": "uint16",
        "indexed": false,
        "internalType": "uint16"
      },
      {
        "name": "poolSupply",
        "type": "uint256",
        "indexed": false,
        "internalType": "uint256"
      },
      {
        "name": "extensionsSupply",
        "type": "uint256",
        "indexed": false,
        "internalType": "uint256"
      },
      {
        "name": "config",
        "type": "tuple",
        "indexed": false,
        "internalType": "struct IArtCoinsFactoryV2.DeploymentConfigV2",
        "components": [
          {
            "name": "token",
            "type": "tuple",
            "internalType": "struct IArtCoinsFactoryV2.TokenConfigV2",
            "components": [
              {
                "name": "tokenAdmin",
                "type": "address",
                "internalType": "address"
              },
              {
                "name": "name",
                "type": "string",
                "internalType": "string"
              },
              {
                "name": "symbol",
                "type": "string",
                "internalType": "string"
              },
              {
                "name": "salt",
                "type": "bytes32",
                "internalType": "bytes32"
              },
              {
                "name": "image",
                "type": "string",
                "internalType": "string"
              },
              {
                "name": "metadata",
                "type": "string",
                "internalType": "string"
              },
              {
                "name": "context",
                "type": "string",
                "internalType": "string"
              },
              {
                "name": "totalSupply",
                "type": "uint256",
                "internalType": "uint256"
              },
              {
                "name": "renderer",
                "type": "address",
                "internalType": "address"
              }
            ]
          },
          {
            "name": "pool",
            "type": "tuple",
            "internalType": "struct IArtCoinsFactoryV2.PoolConfigV2",
            "components": [
              {
                "name": "hook",
                "type": "address",
                "internalType": "address"
              },
              {
                "name": "tickIfToken0IsArtCoin",
                "type": "int24",
                "internalType": "int24"
              },
              {
                "name": "tickSpacing",
                "type": "int24",
                "internalType": "int24"
              },
              {
                "name": "extension",
                "type": "address",
                "internalType": "address"
              },
              {
                "name": "extensionData",
                "type": "bytes",
                "internalType": "bytes"
              }
            ]
          },
          {
            "name": "fee",
            "type": "tuple",
            "internalType": "struct IArtCoinsFactoryV2.FeeConfigV2",
            "components": [
              {
                "name": "lpFee",
                "type": "uint24",
                "internalType": "uint24"
              },
              {
                "name": "baselineSkimBps",
                "type": "uint24",
                "internalType": "uint24"
              },
              {
                "name": "bountyBps",
                "type": "uint16",
                "internalType": "uint16"
              },
              {
                "name": "maxReferralBpsOfVolume",
                "type": "uint24",
                "internalType": "uint24"
              },
              {
                "name": "bountyRecipient",
                "type": "address",
                "internalType": "address payable"
              }
            ]
          },
          {
            "name": "locker",
            "type": "tuple",
            "internalType": "struct IArtCoinsFactoryV2.LockerConfigV2",
            "components": [
              {
                "name": "locker",
                "type": "address",
                "internalType": "address"
              },
              {
                "name": "rewardRecipients",
                "type": "address[]",
                "internalType": "address[]"
              },
              {
                "name": "rewardBps",
                "type": "uint16[]",
                "internalType": "uint16[]"
              },
              {
                "name": "tickLower",
                "type": "int24[]",
                "internalType": "int24[]"
              },
              {
                "name": "tickUpper",
                "type": "int24[]",
                "internalType": "int24[]"
              },
              {
                "name": "positionBps",
                "type": "uint16[]",
                "internalType": "uint16[]"
              }
            ]
          },
          {
            "name": "mev",
            "type": "tuple",
            "internalType": "struct IArtCoinsFactoryV2.MevConfigV2",
            "components": [
              {
                "name": "module",
                "type": "address",
                "internalType": "address"
              },
              {
                "name": "startingSkimBps",
                "type": "uint24",
                "internalType": "uint24"
              },
              {
                "name": "windowSeconds",
                "type": "uint32",
                "internalType": "uint32"
              }
            ]
          },
          {
            "name": "tax",
            "type": "tuple",
            "internalType": "struct IArtCoinsFactoryV2.TaxConfigV2",
            "components": [
              {
                "name": "mode",
                "type": "uint8",
                "internalType": "uint8"
              },
              {
                "name": "taxBps",
                "type": "uint16",
                "internalType": "uint16"
              },
              {
                "name": "taxBpsMax",
                "type": "uint16",
                "internalType": "uint16"
              },
              {
                "name": "taxSink",
                "type": "address",
                "internalType": "address"
              },
              {
                "name": "venueAdmin",
                "type": "address",
                "internalType": "address"
              },
              {
                "name": "exempt",
                "type": "address[]",
                "internalType": "address[]"
              },
              {
                "name": "venues",
                "type": "tuple[]",
                "internalType": "struct IArtCoinsFactoryV2.TaxVenue[]",
                "components": [
                  {
                    "name": "kind",
                    "type": "uint8",
                    "internalType": "uint8"
                  },
                  {
                    "name": "factory",
                    "type": "address",
                    "internalType": "address"
                  },
                  {
                    "name": "initCodeHash",
                    "type": "bytes32",
                    "internalType": "bytes32"
                  },
                  {
                    "name": "counterToken",
                    "type": "address",
                    "internalType": "address"
                  },
                  {
                    "name": "v3Fee",
                    "type": "uint24",
                    "internalType": "uint24"
                  }
                ]
              }
            ]
          },
          {
            "name": "extensions",
            "type": "tuple[]",
            "internalType": "struct IArtCoinsFactoryV2.ExtensionConfigV2[]",
            "components": [
              {
                "name": "extension",
                "type": "address",
                "internalType": "address"
              },
              {
                "name": "msgValue",
                "type": "uint256",
                "internalType": "uint256"
              },
              {
                "name": "extensionBps",
                "type": "uint16",
                "internalType": "uint16"
              },
              {
                "name": "extensionData",
                "type": "bytes",
                "internalType": "bytes"
              }
            ]
          }
        ]
      }
    ],
    "anonymous": false
  },
  {
    "type": "error",
    "name": "BountyBpsTooHigh",
    "inputs": [
      {
        "name": "bountyBps",
        "type": "uint16",
        "internalType": "uint16"
      },
      {
        "name": "max",
        "type": "uint16",
        "internalType": "uint16"
      }
    ]
  },
  {
    "type": "error",
    "name": "ConstantsMismatch",
    "inputs": [
      {
        "name": "module",
        "type": "address",
        "internalType": "address"
      }
    ]
  },
  {
    "type": "error",
    "name": "DeployFeeTooHigh",
    "inputs": []
  },
  {
    "type": "error",
    "name": "Deprecated",
    "inputs": []
  },
  {
    "type": "error",
    "name": "EthTransferFailed",
    "inputs": []
  },
  {
    "type": "error",
    "name": "ExtensionNotEnabled",
    "inputs": []
  },
  {
    "type": "error",
    "name": "HookNotEnabled",
    "inputs": []
  },
  {
    "type": "error",
    "name": "InvalidMevConfig",
    "inputs": []
  },
  {
    "type": "error",
    "name": "InvalidMevModule",
    "inputs": [
      {
        "name": "module",
        "type": "address",
        "internalType": "address"
      }
    ]
  },
  {
    "type": "error",
    "name": "InvalidTaxConfig",
    "inputs": []
  },
  {
    "type": "error",
    "name": "LockerNotEnabled",
    "inputs": []
  },
  {
    "type": "error",
    "name": "MaxExtensionBpsExceeded",
    "inputs": []
  },
  {
    "type": "error",
    "name": "MaxExtensionsExceeded",
    "inputs": []
  },
  {
    "type": "error",
    "name": "MevModuleNotEnabled",
    "inputs": []
  },
  {
    "type": "error",
    "name": "MinProtocolSkimShareTooHigh",
    "inputs": []
  },
  {
    "type": "error",
    "name": "MsgValueMismatch",
    "inputs": [
      {
        "name": "expected",
        "type": "uint256",
        "internalType": "uint256"
      },
      {
        "name": "sent",
        "type": "uint256",
        "internalType": "uint256"
      }
    ]
  },
  {
    "type": "error",
    "name": "NotFound",
    "inputs": []
  },
  {
    "type": "error",
    "name": "ProjectSideBpsMismatch",
    "inputs": []
  },
  {
    "type": "error",
    "name": "ProtocolFeeBpsTooHigh",
    "inputs": []
  },
  {
    "type": "error",
    "name": "TaxSinkNotAllowed",
    "inputs": [
      {
        "name": "sink",
        "type": "address",
        "internalType": "address"
      }
    ]
  },
  {
    "type": "error",
    "name": "TeamFeeRecipientNotSet",
    "inputs": []
  },
  {
    "type": "error",
    "name": "TotalSupplyTooLow",
    "inputs": []
  },
  {
    "type": "error",
    "name": "ZeroAddress",
    "inputs": []
  }
] as const;
