// generated by ui/scripts/gen-abis.mjs from ArtCoinsFactoryV2.sol/ArtCoinsFactoryV2.json, do not edit.
// regenerate: forge build (repo root) then cd ui && npm run gen:abi
export const factoryV2Abi = [
  {
    "type": "function",
    "name": "DEFAULT_MIN_LP_FEE",
    "inputs": [],
    "outputs": [
      {
        "name": "",
        "type": "uint24",
        "internalType": "uint24"
      }
    ],
    "stateMutability": "view"
  },
  {
    "type": "function",
    "name": "STACK_VERSION",
    "inputs": [],
    "outputs": [
      {
        "name": "",
        "type": "uint16",
        "internalType": "uint16"
      }
    ],
    "stateMutability": "view"
  },
  {
    "type": "function",
    "name": "acceptOwnership",
    "inputs": [],
    "outputs": [],
    "stateMutability": "nonpayable"
  },
  {
    "type": "function",
    "name": "configHash",
    "inputs": [
      {
        "name": "c",
        "type": "tuple",
        "internalType": "struct IArtCoinsFactoryV2.DeploymentConfigV2",
        "components": [
          {
            "name": "token",
            "type": "tuple",
            "internalType": "struct IArtCoinsFactoryV2.TokenConfigV2",
            "components": [
              {
                "name": "tokenAdmin",
                "type": "address",
                "internalType": "address"
              },
              {
                "name": "name",
                "type": "string",
                "internalType": "string"
              },
              {
                "name": "symbol",
                "type": "string",
                "internalType": "string"
              },
              {
                "name": "salt",
                "type": "bytes32",
                "internalType": "bytes32"
              },
              {
                "name": "image",
                "type": "string",
                "internalType": "string"
              },
              {
                "name": "metadata",
                "type": "string",
                "internalType": "string"
              },
              {
                "name": "context",
                "type": "string",
                "internalType": "string"
              },
              {
                "name": "totalSupply",
                "type": "uint256",
                "internalType": "uint256"
              },
              {
                "name": "renderer",
                "type": "address",
                "internalType": "address"
              }
            ]
          },
          {
            "name": "pool",
            "type": "tuple",
            "internalType": "struct IArtCoinsFactoryV2.PoolConfigV2",
            "components": [
              {
                "name": "hook",
                "type": "address",
                "internalType": "address"
              },
              {
                "name": "tickIfToken0IsArtCoin",
                "type": "int24",
                "internalType": "int24"
              },
              {
                "name": "tickSpacing",
                "type": "int24",
                "internalType": "int24"
              },
              {
                "name": "extension",
                "type": "address",
                "internalType": "address"
              },
              {
                "name": "extensionData",
                "type": "bytes",
                "internalType": "bytes"
              }
            ]
          },
          {
            "name": "fee",
            "type": "tuple",
            "internalType": "struct IArtCoinsFactoryV2.FeeConfigV2",
            "components": [
              {
                "name": "lpFee",
                "type": "uint24",
                "internalType": "uint24"
              },
              {
                "name": "baselineSkimBps",
                "type": "uint24",
                "internalType": "uint24"
              },
              {
                "name": "bountyBps",
                "type": "uint16",
                "internalType": "uint16"
              },
              {
                "name": "maxReferralBpsOfVolume",
                "type": "uint24",
                "internalType": "uint24"
              },
              {
                "name": "bountyRecipient",
                "type": "address",
                "internalType": "address payable"
              }
            ]
          },
          {
            "name": "locker",
            "type": "tuple",
            "internalType": "struct IArtCoinsFactoryV2.LockerConfigV2",
            "components": [
              {
                "name": "locker",
                "type": "address",
                "internalType": "address"
              },
              {
                "name": "rewardRecipients",
                "type": "address[]",
                "internalType": "address[]"
              },
              {
                "name": "rewardBps",
                "type": "uint16[]",
                "internalType": "uint16[]"
              },
              {
                "name": "tickLower",
                "type": "int24[]",
                "internalType": "int24[]"
              },
              {
                "name": "tickUpper",
                "type": "int24[]",
                "internalType": "int24[]"
              },
              {
                "name": "positionBps",
                "type": "uint16[]",
                "internalType": "uint16[]"
              }
            ]
          },
          {
            "name": "mev",
            "type": "tuple",
            "internalType": "struct IArtCoinsFactoryV2.MevConfigV2",
            "components": [
              {
                "name": "module",
                "type": "address",
                "internalType": "address"
              },
              {
                "name": "startingSkimBps",
                "type": "uint24",
                "internalType": "uint24"
              },
              {
                "name": "windowSeconds",
                "type": "uint32",
                "internalType": "uint32"
              }
            ]
          },
          {
            "name": "restriction",
            "type": "tuple",
            "internalType": "struct IArtCoinsFactoryV2.RestrictionConfigV2",
            "components": [
              {
                "name": "restricted",
                "type": "bool",
                "internalType": "bool"
              },
              {
                "name": "allowed",
                "type": "address[]",
                "internalType": "address[]"
              }
            ]
          },
          {
            "name": "extensions",
            "type": "tuple[]",
            "internalType": "struct IArtCoinsFactoryV2.ExtensionConfigV2[]",
            "components": [
              {
                "name": "extension",
                "type": "address",
                "internalType": "address"
              },
              {
                "name": "msgValue",
                "type": "uint256",
                "internalType": "uint256"
              },
              {
                "name": "extensionBps",
                "type": "uint16",
                "internalType": "uint16"
              },
              {
                "name": "extensionData",
                "type": "bytes",
                "internalType": "bytes"
              }
            ]
          }
        ]
      }
    ],
    "outputs": [
      {
        "name": "",
        "type": "bytes32",
        "internalType": "bytes32"
      }
    ],
    "stateMutability": "pure"
  },
  {
    "type": "function",
    "name": "constantsHash",
    "inputs": [],
    "outputs": [
      {
        "name": "",
        "type": "bytes32",
        "internalType": "bytes32"
      }
    ],
    "stateMutability": "pure"
  },
  {
    "type": "function",
    "name": "defaultAllowed",
    "inputs": [],
    "outputs": [
      {
        "name": "",
        "type": "address[]",
        "internalType": "address[]"
      }
    ],
    "stateMutability": "view"
  },
  {
    "type": "function",
    "name": "defaultProtocolFeeBps",
    "inputs": [],
    "outputs": [
      {
        "name": "",
        "type": "uint16",
        "internalType": "uint16"
      }
    ],
    "stateMutability": "view"
  },
  {
    "type": "function",
    "name": "deployFee",
    "inputs": [],
    "outputs": [
      {
        "name": "",
        "type": "uint256",
        "internalType": "uint256"
      }
    ],
    "stateMutability": "view"
  },
  {
    "type": "function",
    "name": "deployToken",
    "inputs": [
      {
        "name": "c",
        "type": "tuple",
        "internalType": "struct IArtCoinsFactoryV2.DeploymentConfigV2",
        "components": [
          {
            "name": "token",
            "type": "tuple",
            "internalType": "struct IArtCoinsFactoryV2.TokenConfigV2",
            "components": [
              {
                "name": "tokenAdmin",
                "type": "address",
                "internalType": "address"
              },
              {
                "name": "name",
                "type": "string",
                "internalType": "string"
              },
              {
                "name": "symbol",
                "type": "string",
                "internalType": "string"
              },
              {
                "name": "salt",
                "type": "bytes32",
                "internalType": "bytes32"
              },
              {
                "name": "image",
                "type": "string",
                "internalType": "string"
              },
              {
                "name": "metadata",
                "type": "string",
                "internalType": "string"
              },
              {
                "name": "context",
                "type": "string",
                "internalType": "string"
              },
              {
                "name": "totalSupply",
                "type": "uint256",
                "internalType": "uint256"
              },
              {
                "name": "renderer",
                "type": "address",
                "internalType": "address"
              }
            ]
          },
          {
            "name": "pool",
            "type": "tuple",
            "internalType": "struct IArtCoinsFactoryV2.PoolConfigV2",
            "components": [
              {
                "name": "hook",
                "type": "address",
                "internalType": "address"
              },
              {
                "name": "tickIfToken0IsArtCoin",
                "type": "int24",
                "internalType": "int24"
              },
              {
                "name": "tickSpacing",
                "type": "int24",
                "internalType": "int24"
              },
              {
                "name": "extension",
                "type": "address",
                "internalType": "address"
              },
              {
                "name": "extensionData",
                "type": "bytes",
                "internalType": "bytes"
              }
            ]
          },
          {
            "name": "fee",
            "type": "tuple",
            "internalType": "struct IArtCoinsFactoryV2.FeeConfigV2",
            "components": [
              {
                "name": "lpFee",
                "type": "uint24",
                "internalType": "uint24"
              },
              {
                "name": "baselineSkimBps",
                "type": "uint24",
                "internalType": "uint24"
              },
              {
                "name": "bountyBps",
                "type": "uint16",
                "internalType": "uint16"
              },
              {
                "name": "maxReferralBpsOfVolume",
                "type": "uint24",
                "internalType": "uint24"
              },
              {
                "name": "bountyRecipient",
                "type": "address",
                "internalType": "address payable"
              }
            ]
          },
          {
            "name": "locker",
            "type": "tuple",
            "internalType": "struct IArtCoinsFactoryV2.LockerConfigV2",
            "components": [
              {
                "name": "locker",
                "type": "address",
                "internalType": "address"
              },
              {
                "name": "rewardRecipients",
                "type": "address[]",
                "internalType": "address[]"
              },
              {
                "name": "rewardBps",
                "type": "uint16[]",
                "internalType": "uint16[]"
              },
              {
                "name": "tickLower",
                "type": "int24[]",
                "internalType": "int24[]"
              },
              {
                "name": "tickUpper",
                "type": "int24[]",
                "internalType": "int24[]"
              },
              {
                "name": "positionBps",
                "type": "uint16[]",
                "internalType": "uint16[]"
              }
            ]
          },
          {
            "name": "mev",
            "type": "tuple",
            "internalType": "struct IArtCoinsFactoryV2.MevConfigV2",
            "components": [
              {
                "name": "module",
                "type": "address",
                "internalType": "address"
              },
              {
                "name": "startingSkimBps",
                "type": "uint24",
                "internalType": "uint24"
              },
              {
                "name": "windowSeconds",
                "type": "uint32",
                "internalType": "uint32"
              }
            ]
          },
          {
            "name": "restriction",
            "type": "tuple",
            "internalType": "struct IArtCoinsFactoryV2.RestrictionConfigV2",
            "components": [
              {
                "name": "restricted",
                "type": "bool",
                "internalType": "bool"
              },
              {
                "name": "allowed",
                "type": "address[]",
                "internalType": "address[]"
              }
            ]
          },
          {
            "name": "extensions",
            "type": "tuple[]",
            "internalType": "struct IArtCoinsFactoryV2.ExtensionConfigV2[]",
            "components": [
              {
                "name": "extension",
                "type": "address",
                "internalType": "address"
              },
              {
                "name": "msgValue",
                "type": "uint256",
                "internalType": "uint256"
              },
              {
                "name": "extensionBps",
                "type": "uint16",
                "internalType": "uint16"
              },
              {
                "name": "extensionData",
                "type": "bytes",
                "internalType": "bytes"
              }
            ]
          }
        ]
      }
    ],
    "outputs": [
      {
        "name": "token",
        "type": "address",
        "internalType": "address"
      }
    ],
    "stateMutability": "payable"
  },
  {
    "type": "function",
    "name": "deployTokenAsOwner",
    "inputs": [
      {
        "name": "c",
        "type": "tuple",
        "internalType": "struct IArtCoinsFactoryV2.DeploymentConfigV2",
        "components": [
          {
            "name": "token",
            "type": "tuple",
            "internalType": "struct IArtCoinsFactoryV2.TokenConfigV2",
            "components": [
              {
                "name": "tokenAdmin",
                "type": "address",
                "internalType": "address"
              },
              {
                "name": "name",
                "type": "string",
                "internalType": "string"
              },
              {
                "name": "symbol",
                "type": "string",
                "internalType": "string"
              },
              {
                "name": "salt",
                "type": "bytes32",
                "internalType": "bytes32"
              },
              {
                "name": "image",
                "type": "string",
                "internalType": "string"
              },
              {
                "name": "metadata",
                "type": "string",
                "internalType": "string"
              },
              {
                "name": "context",
                "type": "string",
                "internalType": "string"
              },
              {
                "name": "totalSupply",
                "type": "uint256",
                "internalType": "uint256"
              },
              {
                "name": "renderer",
                "type": "address",
                "internalType": "address"
              }
            ]
          },
          {
            "name": "pool",
            "type": "tuple",
            "internalType": "struct IArtCoinsFactoryV2.PoolConfigV2",
            "components": [
              {
                "name": "hook",
                "type": "address",
                "internalType": "address"
              },
              {
                "name": "tickIfToken0IsArtCoin",
                "type": "int24",
                "internalType": "int24"
              },
              {
                "name": "tickSpacing",
                "type": "int24",
                "internalType": "int24"
              },
              {
                "name": "extension",
                "type": "address",
                "internalType": "address"
              },
              {
                "name": "extensionData",
                "type": "bytes",
                "internalType": "bytes"
              }
            ]
          },
          {
            "name": "fee",
            "type": "tuple",
            "internalType": "struct IArtCoinsFactoryV2.FeeConfigV2",
            "components": [
              {
                "name": "lpFee",
                "type": "uint24",
                "internalType": "uint24"
              },
              {
                "name": "baselineSkimBps",
                "type": "uint24",
                "internalType": "uint24"
              },
              {
                "name": "bountyBps",
                "type": "uint16",
                "internalType": "uint16"
              },
              {
                "name": "maxReferralBpsOfVolume",
                "type": "uint24",
                "internalType": "uint24"
              },
              {
                "name": "bountyRecipient",
                "type": "address",
                "internalType": "address payable"
              }
            ]
          },
          {
            "name": "locker",
            "type": "tuple",
            "internalType": "struct IArtCoinsFactoryV2.LockerConfigV2",
            "components": [
              {
                "name": "locker",
                "type": "address",
                "internalType": "address"
              },
              {
                "name": "rewardRecipients",
                "type": "address[]",
                "internalType": "address[]"
              },
              {
                "name": "rewardBps",
                "type": "uint16[]",
                "internalType": "uint16[]"
              },
              {
                "name": "tickLower",
                "type": "int24[]",
                "internalType": "int24[]"
              },
              {
                "name": "tickUpper",
                "type": "int24[]",
                "internalType": "int24[]"
              },
              {
                "name": "positionBps",
                "type": "uint16[]",
                "internalType": "uint16[]"
              }
            ]
          },
          {
            "name": "mev",
            "type": "tuple",
            "internalType": "struct IArtCoinsFactoryV2.MevConfigV2",
            "components": [
              {
                "name": "module",
                "type": "address",
                "internalType": "address"
              },
              {
                "name": "startingSkimBps",
                "type": "uint24",
                "internalType": "uint24"
              },
              {
                "name": "windowSeconds",
                "type": "uint32",
                "internalType": "uint32"
              }
            ]
          },
          {
            "name": "restriction",
            "type": "tuple",
            "internalType": "struct IArtCoinsFactoryV2.RestrictionConfigV2",
            "components": [
              {
                "name": "restricted",
                "type": "bool",
                "internalType": "bool"
              },
              {
                "name": "allowed",
                "type": "address[]",
                "internalType": "address[]"
              }
            ]
          },
          {
            "name": "extensions",
            "type": "tuple[]",
            "internalType": "struct IArtCoinsFactoryV2.ExtensionConfigV2[]",
            "components": [
              {
                "name": "extension",
                "type": "address",
                "internalType": "address"
              },
              {
                "name": "msgValue",
                "type": "uint256",
                "internalType": "uint256"
              },
              {
                "name": "extensionBps",
                "type": "uint16",
                "internalType": "uint16"
              },
              {
                "name": "extensionData",
                "type": "bytes",
                "internalType": "bytes"
              }
            ]
          }
        ]
      },
      {
        "name": "protocolBps",
        "type": "uint16",
        "internalType": "uint16"
      }
    ],
    "outputs": [
      {
        "name": "token",
        "type": "address",
        "internalType": "address"
      }
    ],
    "stateMutability": "payable"
  },
  {
    "type": "function",
    "name": "deploymentInfo",
    "inputs": [
      {
        "name": "token",
        "type": "address",
        "internalType": "address"
      }
    ],
    "outputs": [
      {
        "name": "",
        "type": "tuple",
        "internalType": "struct IArtCoinsFactoryV2.DeploymentInfoV2",
        "components": [
          {
            "name": "token",
            "type": "address",
            "internalType": "address"
          },
          {
            "name": "hook",
            "type": "address",
            "internalType": "address"
          },
          {
            "name": "locker",
            "type": "address",
            "internalType": "address"
          },
          {
            "name": "mevModule",
            "type": "address",
            "internalType": "address"
          },
          {
            "name": "poolId",
            "type": "bytes32",
            "internalType": "PoolId"
          },
          {
            "name": "version",
            "type": "uint16",
            "internalType": "uint16"
          },
          {
            "name": "launchedAt",
            "type": "uint40",
            "internalType": "uint40"
          },
          {
            "name": "extensions",
            "type": "address[]",
            "internalType": "address[]"
          }
        ]
      }
    ],
    "stateMutability": "view"
  },
  {
    "type": "function",
    "name": "deprecated",
    "inputs": [],
    "outputs": [
      {
        "name": "",
        "type": "bool",
        "internalType": "bool"
      }
    ],
    "stateMutability": "view"
  },
  {
    "type": "function",
    "name": "enabledEscrows",
    "inputs": [
      {
        "name": "",
        "type": "address",
        "internalType": "address"
      }
    ],
    "outputs": [
      {
        "name": "",
        "type": "bool",
        "internalType": "bool"
      }
    ],
    "stateMutability": "view"
  },
  {
    "type": "function",
    "name": "enabledExtensions",
    "inputs": [
      {
        "name": "",
        "type": "address",
        "internalType": "address"
      }
    ],
    "outputs": [
      {
        "name": "",
        "type": "bool",
        "internalType": "bool"
      }
    ],
    "stateMutability": "view"
  },
  {
    "type": "function",
    "name": "enabledHooks",
    "inputs": [
      {
        "name": "",
        "type": "address",
        "internalType": "address"
      }
    ],
    "outputs": [
      {
        "name": "",
        "type": "bool",
        "internalType": "bool"
      }
    ],
    "stateMutability": "view"
  },
  {
    "type": "function",
    "name": "enabledLockers",
    "inputs": [
      {
        "name": "",
        "type": "address",
        "internalType": "address"
      }
    ],
    "outputs": [
      {
        "name": "",
        "type": "bool",
        "internalType": "bool"
      }
    ],
    "stateMutability": "view"
  },
  {
    "type": "function",
    "name": "enabledMevModules",
    "inputs": [
      {
        "name": "",
        "type": "address",
        "internalType": "address"
      }
    ],
    "outputs": [
      {
        "name": "",
        "type": "bool",
        "internalType": "bool"
      }
    ],
    "stateMutability": "view"
  },
  {
    "type": "function",
    "name": "isArtCoin",
    "inputs": [
      {
        "name": "",
        "type": "address",
        "internalType": "address"
      }
    ],
    "outputs": [
      {
        "name": "",
        "type": "bool",
        "internalType": "bool"
      }
    ],
    "stateMutability": "view"
  },
  {
    "type": "function",
    "name": "minLpFee",
    "inputs": [],
    "outputs": [
      {
        "name": "",
        "type": "uint24",
        "internalType": "uint24"
      }
    ],
    "stateMutability": "view"
  },
  {
    "type": "function",
    "name": "minProtocolSkimShareBps",
    "inputs": [],
    "outputs": [
      {
        "name": "",
        "type": "uint16",
        "internalType": "uint16"
      }
    ],
    "stateMutability": "view"
  },
  {
    "type": "function",
    "name": "owner",
    "inputs": [],
    "outputs": [
      {
        "name": "",
        "type": "address",
        "internalType": "address"
      }
    ],
    "stateMutability": "view"
  },
  {
    "type": "function",
    "name": "pendingOwner",
    "inputs": [],
    "outputs": [
      {
        "name": "",
        "type": "address",
        "internalType": "address"
      }
    ],
    "stateMutability": "view"
  },
  {
    "type": "function",
    "name": "poolManager",
    "inputs": [],
    "outputs": [
      {
        "name": "",
        "type": "address",
        "internalType": "address"
      }
    ],
    "stateMutability": "view"
  },
  {
    "type": "function",
    "name": "predictToken",
    "inputs": [
      {
        "name": "sender",
        "type": "address",
        "internalType": "address"
      },
      {
        "name": "c",
        "type": "tuple",
        "internalType": "struct IArtCoinsFactoryV2.DeploymentConfigV2",
        "components": [
          {
            "name": "token",
            "type": "tuple",
            "internalType": "struct IArtCoinsFactoryV2.TokenConfigV2",
            "components": [
              {
                "name": "tokenAdmin",
                "type": "address",
                "internalType": "address"
              },
              {
                "name": "name",
                "type": "string",
                "internalType": "string"
              },
              {
                "name": "symbol",
                "type": "string",
                "internalType": "string"
              },
              {
                "name": "salt",
                "type": "bytes32",
                "internalType": "bytes32"
              },
              {
                "name": "image",
                "type": "string",
                "internalType": "string"
              },
              {
                "name": "metadata",
                "type": "string",
                "internalType": "string"
              },
              {
                "name": "context",
                "type": "string",
                "internalType": "string"
              },
              {
                "name": "totalSupply",
                "type": "uint256",
                "internalType": "uint256"
              },
              {
                "name": "renderer",
                "type": "address",
                "internalType": "address"
              }
            ]
          },
          {
            "name": "pool",
            "type": "tuple",
            "internalType": "struct IArtCoinsFactoryV2.PoolConfigV2",
            "components": [
              {
                "name": "hook",
                "type": "address",
                "internalType": "address"
              },
              {
                "name": "tickIfToken0IsArtCoin",
                "type": "int24",
                "internalType": "int24"
              },
              {
                "name": "tickSpacing",
                "type": "int24",
                "internalType": "int24"
              },
              {
                "name": "extension",
                "type": "address",
                "internalType": "address"
              },
              {
                "name": "extensionData",
                "type": "bytes",
                "internalType": "bytes"
              }
            ]
          },
          {
            "name": "fee",
            "type": "tuple",
            "internalType": "struct IArtCoinsFactoryV2.FeeConfigV2",
            "components": [
              {
                "name": "lpFee",
                "type": "uint24",
                "internalType": "uint24"
              },
              {
                "name": "baselineSkimBps",
                "type": "uint24",
                "internalType": "uint24"
              },
              {
                "name": "bountyBps",
                "type": "uint16",
                "internalType": "uint16"
              },
              {
                "name": "maxReferralBpsOfVolume",
                "type": "uint24",
                "internalType": "uint24"
              },
              {
                "name": "bountyRecipient",
                "type": "address",
                "internalType": "address payable"
              }
            ]
          },
          {
            "name": "locker",
            "type": "tuple",
            "internalType": "struct IArtCoinsFactoryV2.LockerConfigV2",
            "components": [
              {
                "name": "locker",
                "type": "address",
                "internalType": "address"
              },
              {
                "name": "rewardRecipients",
                "type": "address[]",
                "internalType": "address[]"
              },
              {
                "name": "rewardBps",
                "type": "uint16[]",
                "internalType": "uint16[]"
              },
              {
                "name": "tickLower",
                "type": "int24[]",
                "internalType": "int24[]"
              },
              {
                "name": "tickUpper",
                "type": "int24[]",
                "internalType": "int24[]"
              },
              {
                "name": "positionBps",
                "type": "uint16[]",
                "internalType": "uint16[]"
              }
            ]
          },
          {
            "name": "mev",
            "type": "tuple",
            "internalType": "struct IArtCoinsFactoryV2.MevConfigV2",
            "components": [
              {
                "name": "module",
                "type": "address",
                "internalType": "address"
              },
              {
                "name": "startingSkimBps",
                "type": "uint24",
                "internalType": "uint24"
              },
              {
                "name": "windowSeconds",
                "type": "uint32",
                "internalType": "uint32"
              }
            ]
          },
          {
            "name": "restriction",
            "type": "tuple",
            "internalType": "struct IArtCoinsFactoryV2.RestrictionConfigV2",
            "components": [
              {
                "name": "restricted",
                "type": "bool",
                "internalType": "bool"
              },
              {
                "name": "allowed",
                "type": "address[]",
                "internalType": "address[]"
              }
            ]
          },
          {
            "name": "extensions",
            "type": "tuple[]",
            "internalType": "struct IArtCoinsFactoryV2.ExtensionConfigV2[]",
            "components": [
              {
                "name": "extension",
                "type": "address",
                "internalType": "address"
              },
              {
                "name": "msgValue",
                "type": "uint256",
                "internalType": "uint256"
              },
              {
                "name": "extensionBps",
                "type": "uint16",
                "internalType": "uint16"
              },
              {
                "name": "extensionData",
                "type": "bytes",
                "internalType": "bytes"
              }
            ]
          }
        ]
      }
    ],
    "outputs": [
      {
        "name": "",
        "type": "address",
        "internalType": "address"
      }
    ],
    "stateMutability": "view"
  },
  {
    "type": "function",
    "name": "protocolRecipient",
    "inputs": [],
    "outputs": [
      {
        "name": "",
        "type": "address",
        "internalType": "address payable"
      }
    ],
    "stateMutability": "view"
  },
  {
    "type": "function",
    "name": "referralPayout",
    "inputs": [],
    "outputs": [
      {
        "name": "",
        "type": "address",
        "internalType": "address payable"
      }
    ],
    "stateMutability": "view"
  },
  {
    "type": "function",
    "name": "renounceOwnership",
    "inputs": [],
    "outputs": [],
    "stateMutability": "view"
  },
  {
    "type": "function",
    "name": "rescue",
    "inputs": [
      {
        "name": "token",
        "type": "address",
        "internalType": "address"
      },
      {
        "name": "to",
        "type": "address",
        "internalType": "address"
      },
      {
        "name": "amount",
        "type": "uint256",
        "internalType": "uint256"
      }
    ],
    "outputs": [],
    "stateMutability": "nonpayable"
  },
  {
    "type": "function",
    "name": "setDefaultAllowed",
    "inputs": [
      {
        "name": "accounts",
        "type": "address[]",
        "internalType": "address[]"
      }
    ],
    "outputs": [],
    "stateMutability": "nonpayable"
  },
  {
    "type": "function",
    "name": "setDefaultProtocolFeeBps",
    "inputs": [
      {
        "name": "bps",
        "type": "uint16",
        "internalType": "uint16"
      }
    ],
    "outputs": [],
    "stateMutability": "nonpayable"
  },
  {
    "type": "function",
    "name": "setDeployFee",
    "inputs": [
      {
        "name": "fee",
        "type": "uint256",
        "internalType": "uint256"
      }
    ],
    "outputs": [],
    "stateMutability": "nonpayable"
  },
  {
    "type": "function",
    "name": "setDeprecated",
    "inputs": [
      {
        "name": "deprecated_",
        "type": "bool",
        "internalType": "bool"
      }
    ],
    "outputs": [],
    "stateMutability": "nonpayable"
  },
  {
    "type": "function",
    "name": "setEscrow",
    "inputs": [
      {
        "name": "escrow",
        "type": "address",
        "internalType": "address"
      },
      {
        "name": "enabled",
        "type": "bool",
        "internalType": "bool"
      }
    ],
    "outputs": [],
    "stateMutability": "nonpayable"
  },
  {
    "type": "function",
    "name": "setExtension",
    "inputs": [
      {
        "name": "extension",
        "type": "address",
        "internalType": "address"
      },
      {
        "name": "enabled",
        "type": "bool",
        "internalType": "bool"
      }
    ],
    "outputs": [],
    "stateMutability": "nonpayable"
  },
  {
    "type": "function",
    "name": "setHook",
    "inputs": [
      {
        "name": "hook",
        "type": "address",
        "internalType": "address"
      },
      {
        "name": "enabled",
        "type": "bool",
        "internalType": "bool"
      }
    ],
    "outputs": [],
    "stateMutability": "nonpayable"
  },
  {
    "type": "function",
    "name": "setLocker",
    "inputs": [
      {
        "name": "locker",
        "type": "address",
        "internalType": "address"
      },
      {
        "name": "enabled",
        "type": "bool",
        "internalType": "bool"
      }
    ],
    "outputs": [],
    "stateMutability": "nonpayable"
  },
  {
    "type": "function",
    "name": "setMevModule",
    "inputs": [
      {
        "name": "module",
        "type": "address",
        "internalType": "address"
      },
      {
        "name": "enabled",
        "type": "bool",
        "internalType": "bool"
      }
    ],
    "outputs": [],
    "stateMutability": "nonpayable"
  },
  {
    "type": "function",
    "name": "setMinLpFee",
    "inputs": [
      {
        "name": "fee",
        "type": "uint24",
        "internalType": "uint24"
      }
    ],
    "outputs": [],
    "stateMutability": "nonpayable"
  },
  {
    "type": "function",
    "name": "setMinProtocolSkimShareBps",
    "inputs": [
      {
        "name": "bps",
        "type": "uint16",
        "internalType": "uint16"
      }
    ],
    "outputs": [],
    "stateMutability": "nonpayable"
  },
  {
    "type": "function",
    "name": "setProtocolRecipient",
    "inputs": [
      {
        "name": "recipient",
        "type": "address",
        "internalType": "address payable"
      }
    ],
    "outputs": [],
    "stateMutability": "nonpayable"
  },
  {
    "type": "function",
    "name": "setReferralPayout",
    "inputs": [
      {
        "name": "payout",
        "type": "address",
        "internalType": "address payable"
      }
    ],
    "outputs": [],
    "stateMutability": "nonpayable"
  },
  {
    "type": "function",
    "name": "setTeamFeeRecipient",
    "inputs": [
      {
        "name": "recipient",
        "type": "address",
        "internalType": "address"
      }
    ],
    "outputs": [],
    "stateMutability": "nonpayable"
  },
  {
    "type": "function",
    "name": "setTokenDeployer",
    "inputs": [
      {
        "name": "deployer",
        "type": "address",
        "internalType": "address"
      }
    ],
    "outputs": [],
    "stateMutability": "nonpayable"
  },
  {
    "type": "function",
    "name": "teamFeeRecipient",
    "inputs": [],
    "outputs": [
      {
        "name": "",
        "type": "address",
        "internalType": "address"
      }
    ],
    "stateMutability": "view"
  },
  {
    "type": "function",
    "name": "tokenDeployer",
    "inputs": [],
    "outputs": [
      {
        "name": "",
        "type": "address",
        "internalType": "address"
      }
    ],
    "stateMutability": "view"
  },
  {
    "type": "function",
    "name": "transferOwnership",
    "inputs": [
      {
        "name": "newOwner",
        "type": "address",
        "internalType": "address"
      }
    ],
    "outputs": [],
    "stateMutability": "nonpayable"
  },
  {
    "type": "event",
    "name": "DefaultAllowedSet",
    "inputs": [
      {
        "name": "accounts",
        "type": "address[]",
        "indexed": false,
        "internalType": "address[]"
      }
    ],
    "anonymous": false
  },
  {
    "type": "event",
    "name": "DefaultProtocolFeeBpsSet",
    "inputs": [
      {
        "name": "oldBps",
        "type": "uint16",
        "indexed": false,
        "internalType": "uint16"
      },
      {
        "name": "newBps",
        "type": "uint16",
        "indexed": false,
        "internalType": "uint16"
      }
    ],
    "anonymous": false
  },
  {
    "type": "event",
    "name": "DeployFeePaid",
    "inputs": [
      {
        "name": "recipient",
        "type": "address",
        "indexed": true,
        "internalType": "address"
      },
      {
        "name": "amount",
        "type": "uint256",
        "indexed": false,
        "internalType": "uint256"
      }
    ],
    "anonymous": false
  },
  {
    "type": "event",
    "name": "DeployFeeSet",
    "inputs": [
      {
        "name": "oldFee",
        "type": "uint256",
        "indexed": false,
        "internalType": "uint256"
      },
      {
        "name": "newFee",
        "type": "uint256",
        "indexed": false,
        "internalType": "uint256"
      }
    ],
    "anonymous": false
  },
  {
    "type": "event",
    "name": "DeprecatedSet",
    "inputs": [
      {
        "name": "deprecated",
        "type": "bool",
        "indexed": false,
        "internalType": "bool"
      }
    ],
    "anonymous": false
  },
  {
    "type": "event",
    "name": "EscrowSet",
    "inputs": [
      {
        "name": "escrow",
        "type": "address",
        "indexed": true,
        "internalType": "address"
      },
      {
        "name": "enabled",
        "type": "bool",
        "indexed": false,
        "internalType": "bool"
      }
    ],
    "anonymous": false
  },
  {
    "type": "event",
    "name": "ExtensionSet",
    "inputs": [
      {
        "name": "extension",
        "type": "address",
        "indexed": true,
        "internalType": "address"
      },
      {
        "name": "enabled",
        "type": "bool",
        "indexed": false,
        "internalType": "bool"
      }
    ],
    "anonymous": false
  },
  {
    "type": "event",
    "name": "ExtensionTriggered",
    "inputs": [
      {
        "name": "token",
        "type": "address",
        "indexed": true,
        "internalType": "address"
      },
      {
        "name": "extension",
        "type": "address",
        "indexed": true,
        "internalType": "address"
      },
      {
        "name": "extensionSupply",
        "type": "uint256",
        "indexed": false,
        "internalType": "uint256"
      },
      {
        "name": "msgValue",
        "type": "uint256",
        "indexed": false,
        "internalType": "uint256"
      }
    ],
    "anonymous": false
  },
  {
    "type": "event",
    "name": "HookSet",
    "inputs": [
      {
        "name": "hook",
        "type": "address",
        "indexed": true,
        "internalType": "address"
      },
      {
        "name": "enabled",
        "type": "bool",
        "indexed": false,
        "internalType": "bool"
      }
    ],
    "anonymous": false
  },
  {
    "type": "event",
    "name": "LockerSet",
    "inputs": [
      {
        "name": "locker",
        "type": "address",
        "indexed": true,
        "internalType": "address"
      },
      {
        "name": "enabled",
        "type": "bool",
        "indexed": false,
        "internalType": "bool"
      }
    ],
    "anonymous": false
  },
  {
    "type": "event",
    "name": "MevModuleSet",
    "inputs": [
      {
        "name": "module",
        "type": "address",
        "indexed": true,
        "internalType": "address"
      },
      {
        "name": "enabled",
        "type": "bool",
        "indexed": false,
        "internalType": "bool"
      }
    ],
    "anonymous": false
  },
  {
    "type": "event",
    "name": "MinLpFeeSet",
    "inputs": [
      {
        "name": "oldFee",
        "type": "uint24",
        "indexed": false,
        "internalType": "uint24"
      },
      {
        "name": "newFee",
        "type": "uint24",
        "indexed": false,
        "internalType": "uint24"
      }
    ],
    "anonymous": false
  },
  {
    "type": "event",
    "name": "MinProtocolSkimShareBpsSet",
    "inputs": [
      {
        "name": "oldBps",
        "type": "uint16",
        "indexed": false,
        "internalType": "uint16"
      },
      {
        "name": "newBps",
        "type": "uint16",
        "indexed": false,
        "internalType": "uint16"
      }
    ],
    "anonymous": false
  },
  {
    "type": "event",
    "name": "OwnershipTransferStarted",
    "inputs": [
      {
        "name": "previousOwner",
        "type": "address",
        "indexed": true,
        "internalType": "address"
      },
      {
        "name": "newOwner",
        "type": "address",
        "indexed": true,
        "internalType": "address"
      }
    ],
    "anonymous": false
  },
  {
    "type": "event",
    "name": "OwnershipTransferred",
    "inputs": [
      {
        "name": "previousOwner",
        "type": "address",
        "indexed": true,
        "internalType": "address"
      },
      {
        "name": "newOwner",
        "type": "address",
        "indexed": true,
        "internalType": "address"
      }
    ],
    "anonymous": false
  },
  {
    "type": "event",
    "name": "ProtocolRecipientSet",
    "inputs": [
      {
        "name": "oldRecipient",
        "type": "address",
        "indexed": true,
        "internalType": "address"
      },
      {
        "name": "newRecipient",
        "type": "address",
        "indexed": true,
        "internalType": "address"
      }
    ],
    "anonymous": false
  },
  {
    "type": "event",
    "name": "ReferralPayoutSet",
    "inputs": [
      {
        "name": "oldPayout",
        "type": "address",
        "indexed": true,
        "internalType": "address"
      },
      {
        "name": "newPayout",
        "type": "address",
        "indexed": true,
        "internalType": "address"
      }
    ],
    "anonymous": false
  },
  {
    "type": "event",
    "name": "Rescued",
    "inputs": [
      {
        "name": "token",
        "type": "address",
        "indexed": true,
        "internalType": "address"
      },
      {
        "name": "to",
        "type": "address",
        "indexed": true,
        "internalType": "address"
      },
      {
        "name": "amount",
        "type": "uint256",
        "indexed": false,
        "internalType": "uint256"
      }
    ],
    "anonymous": false
  },
  {
    "type": "event",
    "name": "TeamFeeRecipientSet",
    "inputs": [
      {
        "name": "oldRecipient",
        "type": "address",
        "indexed": true,
        "internalType": "address"
      },
      {
        "name": "newRecipient",
        "type": "address",
        "indexed": true,
        "internalType": "address"
      }
    ],
    "anonymous": false
  },
  {
    "type": "event",
    "name": "TokenCreatedV2",
    "inputs": [
      {
        "name": "sender",
        "type": "address",
        "indexed": true,
        "internalType": "address"
      },
      {
        "name": "token",
        "type": "address",
        "indexed": true,
        "internalType": "address"
      },
      {
        "name": "poolId",
        "type": "bytes32",
        "indexed": true,
        "internalType": "PoolId"
      },
      {
        "name": "stackVersion",
        "type": "uint16",
        "indexed": false,
        "internalType": "uint16"
      },
      {
        "name": "configHash",
        "type": "bytes32",
        "indexed": false,
        "internalType": "bytes32"
      },
      {
        "name": "protocolRecipient",
        "type": "address",
        "indexed": false,
        "internalType": "address"
      },
      {
        "name": "referralPayout",
        "type": "address",
        "indexed": false,
        "internalType": "address"
      },
      {
        "name": "protocolBps",
        "type": "uint16",
        "indexed": false,
        "internalType": "uint16"
      },
      {
        "name": "poolSupply",
        "type": "uint256",
        "indexed": false,
        "internalType": "uint256"
      },
      {
        "name": "extensionsSupply",
        "type": "uint256",
        "indexed": false,
        "internalType": "uint256"
      },
      {
        "name": "config",
        "type": "tuple",
        "indexed": false,
        "internalType": "struct IArtCoinsFactoryV2.DeploymentConfigV2",
        "components": [
          {
            "name": "token",
            "type": "tuple",
            "internalType": "struct IArtCoinsFactoryV2.TokenConfigV2",
            "components": [
              {
                "name": "tokenAdmin",
                "type": "address",
                "internalType": "address"
              },
              {
                "name": "name",
                "type": "string",
                "internalType": "string"
              },
              {
                "name": "symbol",
                "type": "string",
                "internalType": "string"
              },
              {
                "name": "salt",
                "type": "bytes32",
                "internalType": "bytes32"
              },
              {
                "name": "image",
                "type": "string",
                "internalType": "string"
              },
              {
                "name": "metadata",
                "type": "string",
                "internalType": "string"
              },
              {
                "name": "context",
                "type": "string",
                "internalType": "string"
              },
              {
                "name": "totalSupply",
                "type": "uint256",
                "internalType": "uint256"
              },
              {
                "name": "renderer",
                "type": "address",
                "internalType": "address"
              }
            ]
          },
          {
            "name": "pool",
            "type": "tuple",
            "internalType": "struct IArtCoinsFactoryV2.PoolConfigV2",
            "components": [
              {
                "name": "hook",
                "type": "address",
                "internalType": "address"
              },
              {
                "name": "tickIfToken0IsArtCoin",
                "type": "int24",
                "internalType": "int24"
              },
              {
                "name": "tickSpacing",
                "type": "int24",
                "internalType": "int24"
              },
              {
                "name": "extension",
                "type": "address",
                "internalType": "address"
              },
              {
                "name": "extensionData",
                "type": "bytes",
                "internalType": "bytes"
              }
            ]
          },
          {
            "name": "fee",
            "type": "tuple",
            "internalType": "struct IArtCoinsFactoryV2.FeeConfigV2",
            "components": [
              {
                "name": "lpFee",
                "type": "uint24",
                "internalType": "uint24"
              },
              {
                "name": "baselineSkimBps",
                "type": "uint24",
                "internalType": "uint24"
              },
              {
                "name": "bountyBps",
                "type": "uint16",
                "internalType": "uint16"
              },
              {
                "name": "maxReferralBpsOfVolume",
                "type": "uint24",
                "internalType": "uint24"
              },
              {
                "name": "bountyRecipient",
                "type": "address",
                "internalType": "address payable"
              }
            ]
          },
          {
            "name": "locker",
            "type": "tuple",
            "internalType": "struct IArtCoinsFactoryV2.LockerConfigV2",
            "components": [
              {
                "name": "locker",
                "type": "address",
                "internalType": "address"
              },
              {
                "name": "rewardRecipients",
                "type": "address[]",
                "internalType": "address[]"
              },
              {
                "name": "rewardBps",
                "type": "uint16[]",
                "internalType": "uint16[]"
              },
              {
                "name": "tickLower",
                "type": "int24[]",
                "internalType": "int24[]"
              },
              {
                "name": "tickUpper",
                "type": "int24[]",
                "internalType": "int24[]"
              },
              {
                "name": "positionBps",
                "type": "uint16[]",
                "internalType": "uint16[]"
              }
            ]
          },
          {
            "name": "mev",
            "type": "tuple",
            "internalType": "struct IArtCoinsFactoryV2.MevConfigV2",
            "components": [
              {
                "name": "module",
                "type": "address",
                "internalType": "address"
              },
              {
                "name": "startingSkimBps",
                "type": "uint24",
                "internalType": "uint24"
              },
              {
                "name": "windowSeconds",
                "type": "uint32",
                "internalType": "uint32"
              }
            ]
          },
          {
            "name": "restriction",
            "type": "tuple",
            "internalType": "struct IArtCoinsFactoryV2.RestrictionConfigV2",
            "components": [
              {
                "name": "restricted",
                "type": "bool",
                "internalType": "bool"
              },
              {
                "name": "allowed",
                "type": "address[]",
                "internalType": "address[]"
              }
            ]
          },
          {
            "name": "extensions",
            "type": "tuple[]",
            "internalType": "struct IArtCoinsFactoryV2.ExtensionConfigV2[]",
            "components": [
              {
                "name": "extension",
                "type": "address",
                "internalType": "address"
              },
              {
                "name": "msgValue",
                "type": "uint256",
                "internalType": "uint256"
              },
              {
                "name": "extensionBps",
                "type": "uint16",
                "internalType": "uint16"
              },
              {
                "name": "extensionData",
                "type": "bytes",
                "internalType": "bytes"
              }
            ]
          }
        ]
      }
    ],
    "anonymous": false
  },
  {
    "type": "event",
    "name": "TokenDeployerSet",
    "inputs": [
      {
        "name": "oldDeployer",
        "type": "address",
        "indexed": true,
        "internalType": "address"
      },
      {
        "name": "newDeployer",
        "type": "address",
        "indexed": true,
        "internalType": "address"
      }
    ],
    "anonymous": false
  },
  {
    "type": "error",
    "name": "ArrayLengthMismatch",
    "inputs": []
  },
  {
    "type": "error",
    "name": "BountyBpsTooHigh",
    "inputs": [
      {
        "name": "bountyBps",
        "type": "uint16",
        "internalType": "uint16"
      },
      {
        "name": "max",
        "type": "uint16",
        "internalType": "uint16"
      }
    ]
  },
  {
    "type": "error",
    "name": "ConstantsMismatch",
    "inputs": [
      {
        "name": "module",
        "type": "address",
        "internalType": "address"
      }
    ]
  },
  {
    "type": "error",
    "name": "DeployFeeTooHigh",
    "inputs": []
  },
  {
    "type": "error",
    "name": "DeployerNotSet",
    "inputs": []
  },
  {
    "type": "error",
    "name": "Deprecated",
    "inputs": []
  },
  {
    "type": "error",
    "name": "EthTransferFailed",
    "inputs": []
  },
  {
    "type": "error",
    "name": "ExtensionNotEnabled",
    "inputs": []
  },
  {
    "type": "error",
    "name": "FeeConfigOutOfBounds",
    "inputs": []
  },
  {
    "type": "error",
    "name": "HookNotEnabled",
    "inputs": []
  },
  {
    "type": "error",
    "name": "InvalidDeployer",
    "inputs": [
      {
        "name": "deployer",
        "type": "address",
        "internalType": "address"
      }
    ]
  },
  {
    "type": "error",
    "name": "InvalidMevConfig",
    "inputs": []
  },
  {
    "type": "error",
    "name": "InvalidMevModule",
    "inputs": [
      {
        "name": "module",
        "type": "address",
        "internalType": "address"
      }
    ]
  },
  {
    "type": "error",
    "name": "InvalidPositions",
    "inputs": []
  },
  {
    "type": "error",
    "name": "InvalidRenderer",
    "inputs": []
  },
  {
    "type": "error",
    "name": "InvalidRestrictionConfig",
    "inputs": []
  },
  {
    "type": "error",
    "name": "InvalidRewardSlots",
    "inputs": []
  },
  {
    "type": "error",
    "name": "LockerNotEnabled",
    "inputs": []
  },
  {
    "type": "error",
    "name": "LpFeeBelowMinimum",
    "inputs": []
  },
  {
    "type": "error",
    "name": "MaxExtensionBpsExceeded",
    "inputs": []
  },
  {
    "type": "error",
    "name": "MaxExtensionsExceeded",
    "inputs": []
  },
  {
    "type": "error",
    "name": "MevModuleNotEnabled",
    "inputs": []
  },
  {
    "type": "error",
    "name": "MinLpFeeTooHigh",
    "inputs": []
  },
  {
    "type": "error",
    "name": "MinProtocolSkimShareTooHigh",
    "inputs": []
  },
  {
    "type": "error",
    "name": "MsgValueMismatch",
    "inputs": [
      {
        "name": "expected",
        "type": "uint256",
        "internalType": "uint256"
      },
      {
        "name": "sent",
        "type": "uint256",
        "internalType": "uint256"
      }
    ]
  },
  {
    "type": "error",
    "name": "NotFound",
    "inputs": []
  },
  {
    "type": "error",
    "name": "OwnableInvalidOwner",
    "inputs": [
      {
        "name": "owner",
        "type": "address",
        "internalType": "address"
      }
    ]
  },
  {
    "type": "error",
    "name": "OwnableUnauthorizedAccount",
    "inputs": [
      {
        "name": "account",
        "type": "address",
        "internalType": "address"
      }
    ]
  },
  {
    "type": "error",
    "name": "PoolManagerMismatch",
    "inputs": [
      {
        "name": "hook",
        "type": "address",
        "internalType": "address"
      }
    ]
  },
  {
    "type": "error",
    "name": "ProjectSideBpsMismatch",
    "inputs": []
  },
  {
    "type": "error",
    "name": "ProtocolFeeBpsTooHigh",
    "inputs": []
  },
  {
    "type": "error",
    "name": "RecipientCannotReceive",
    "inputs": [
      {
        "name": "recipient",
        "type": "address",
        "internalType": "address"
      }
    ]
  },
  {
    "type": "error",
    "name": "ReentrancyGuardReentrantCall",
    "inputs": []
  },
  {
    "type": "error",
    "name": "ReferralCapAboveProtocolFloor",
    "inputs": []
  },
  {
    "type": "error",
    "name": "RenounceDisabled",
    "inputs": []
  },
  {
    "type": "error",
    "name": "SafeERC20FailedOperation",
    "inputs": [
      {
        "name": "token",
        "type": "address",
        "internalType": "address"
      }
    ]
  },
  {
    "type": "error",
    "name": "StringTooLong",
    "inputs": [
      {
        "name": "field",
        "type": "uint8",
        "internalType": "uint8"
      },
      {
        "name": "len",
        "type": "uint256",
        "internalType": "uint256"
      }
    ]
  },
  {
    "type": "error",
    "name": "SupplyNotPulled",
    "inputs": [
      {
        "name": "puller",
        "type": "address",
        "internalType": "address"
      }
    ]
  },
  {
    "type": "error",
    "name": "TeamFeeRecipientNotSet",
    "inputs": []
  },
  {
    "type": "error",
    "name": "TotalSupplyTooLow",
    "inputs": []
  },
  {
    "type": "error",
    "name": "ZeroAddress",
    "inputs": []
  }
] as const;
