// generated by ui/scripts/gen-abis.mjs from IArtCoinsVaultV2.sol/IArtCoinsVaultV2.json, do not edit.
// regenerate: forge build (repo root) then cd ui && npm run gen:abi
export const vaultV2Abi = [
  {
    "type": "function",
    "name": "allocation",
    "inputs": [
      {
        "name": "token",
        "type": "address",
        "internalType": "address"
      },
      {
        "name": "index",
        "type": "uint256",
        "internalType": "uint256"
      }
    ],
    "outputs": [
      {
        "name": "",
        "type": "tuple",
        "internalType": "struct IArtCoinsVaultV2.Allocation",
        "components": [
          {
            "name": "beneficiary",
            "type": "address",
            "internalType": "address"
          },
          {
            "name": "amountTotal",
            "type": "uint256",
            "internalType": "uint256"
          },
          {
            "name": "amountClaimed",
            "type": "uint256",
            "internalType": "uint256"
          },
          {
            "name": "lockupEndTime",
            "type": "uint256",
            "internalType": "uint256"
          },
          {
            "name": "vestingEndTime",
            "type": "uint256",
            "internalType": "uint256"
          }
        ]
      }
    ],
    "stateMutability": "view"
  },
  {
    "type": "function",
    "name": "amountAvailableToClaim",
    "inputs": [
      {
        "name": "token",
        "type": "address",
        "internalType": "address"
      },
      {
        "name": "index",
        "type": "uint256",
        "internalType": "uint256"
      }
    ],
    "outputs": [
      {
        "name": "",
        "type": "uint256",
        "internalType": "uint256"
      }
    ],
    "stateMutability": "view"
  },
  {
    "type": "function",
    "name": "claim",
    "inputs": [
      {
        "name": "token",
        "type": "address",
        "internalType": "address"
      },
      {
        "name": "index",
        "type": "uint256",
        "internalType": "uint256"
      }
    ],
    "outputs": [],
    "stateMutability": "nonpayable"
  },
  {
    "type": "function",
    "name": "constantsHash",
    "inputs": [],
    "outputs": [
      {
        "name": "",
        "type": "bytes32",
        "internalType": "bytes32"
      }
    ],
    "stateMutability": "pure"
  },
  {
    "type": "function",
    "name": "receiveTokens",
    "inputs": [
      {
        "name": "config",
        "type": "tuple",
        "internalType": "struct IArtCoinsFactoryV2.DeploymentConfigV2",
        "components": [
          {
            "name": "token",
            "type": "tuple",
            "internalType": "struct IArtCoinsFactoryV2.TokenConfigV2",
            "components": [
              {
                "name": "tokenAdmin",
                "type": "address",
                "internalType": "address"
              },
              {
                "name": "name",
                "type": "string",
                "internalType": "string"
              },
              {
                "name": "symbol",
                "type": "string",
                "internalType": "string"
              },
              {
                "name": "salt",
                "type": "bytes32",
                "internalType": "bytes32"
              },
              {
                "name": "image",
                "type": "string",
                "internalType": "string"
              },
              {
                "name": "metadata",
                "type": "string",
                "internalType": "string"
              },
              {
                "name": "context",
                "type": "string",
                "internalType": "string"
              },
              {
                "name": "totalSupply",
                "type": "uint256",
                "internalType": "uint256"
              },
              {
                "name": "renderer",
                "type": "address",
                "internalType": "address"
              }
            ]
          },
          {
            "name": "pool",
            "type": "tuple",
            "internalType": "struct IArtCoinsFactoryV2.PoolConfigV2",
            "components": [
              {
                "name": "hook",
                "type": "address",
                "internalType": "address"
              },
              {
                "name": "tickIfToken0IsArtCoin",
                "type": "int24",
                "internalType": "int24"
              },
              {
                "name": "tickSpacing",
                "type": "int24",
                "internalType": "int24"
              },
              {
                "name": "extension",
                "type": "address",
                "internalType": "address"
              },
              {
                "name": "extensionData",
                "type": "bytes",
                "internalType": "bytes"
              }
            ]
          },
          {
            "name": "fee",
            "type": "tuple",
            "internalType": "struct IArtCoinsFactoryV2.FeeConfigV2",
            "components": [
              {
                "name": "lpFee",
                "type": "uint24",
                "internalType": "uint24"
              },
              {
                "name": "baselineSkimBps",
                "type": "uint24",
                "internalType": "uint24"
              },
              {
                "name": "bountyBps",
                "type": "uint16",
                "internalType": "uint16"
              },
              {
                "name": "maxReferralBpsOfVolume",
                "type": "uint24",
                "internalType": "uint24"
              },
              {
                "name": "bountyRecipient",
                "type": "address",
                "internalType": "address payable"
              }
            ]
          },
          {
            "name": "locker",
            "type": "tuple",
            "internalType": "struct IArtCoinsFactoryV2.LockerConfigV2",
            "components": [
              {
                "name": "locker",
                "type": "address",
                "internalType": "address"
              },
              {
                "name": "rewardRecipients",
                "type": "address[]",
                "internalType": "address[]"
              },
              {
                "name": "rewardBps",
                "type": "uint16[]",
                "internalType": "uint16[]"
              },
              {
                "name": "tickLower",
                "type": "int24[]",
                "internalType": "int24[]"
              },
              {
                "name": "tickUpper",
                "type": "int24[]",
                "internalType": "int24[]"
              },
              {
                "name": "positionBps",
                "type": "uint16[]",
                "internalType": "uint16[]"
              }
            ]
          },
          {
            "name": "mev",
            "type": "tuple",
            "internalType": "struct IArtCoinsFactoryV2.MevConfigV2",
            "components": [
              {
                "name": "module",
                "type": "address",
                "internalType": "address"
              },
              {
                "name": "startingSkimBps",
                "type": "uint24",
                "internalType": "uint24"
              },
              {
                "name": "windowSeconds",
                "type": "uint32",
                "internalType": "uint32"
              }
            ]
          },
          {
            "name": "tax",
            "type": "tuple",
            "internalType": "struct IArtCoinsFactoryV2.TaxConfigV2",
            "components": [
              {
                "name": "mode",
                "type": "uint8",
                "internalType": "uint8"
              },
              {
                "name": "taxBps",
                "type": "uint16",
                "internalType": "uint16"
              },
              {
                "name": "taxBpsMax",
                "type": "uint16",
                "internalType": "uint16"
              },
              {
                "name": "taxSink",
                "type": "address",
                "internalType": "address"
              },
              {
                "name": "venueAdmin",
                "type": "address",
                "internalType": "address"
              },
              {
                "name": "exempt",
                "type": "address[]",
                "internalType": "address[]"
              },
              {
                "name": "venues",
                "type": "tuple[]",
                "internalType": "struct IArtCoinsFactoryV2.TaxVenue[]",
                "components": [
                  {
                    "name": "kind",
                    "type": "uint8",
                    "internalType": "uint8"
                  },
                  {
                    "name": "factory",
                    "type": "address",
                    "internalType": "address"
                  },
                  {
                    "name": "initCodeHash",
                    "type": "bytes32",
                    "internalType": "bytes32"
                  },
                  {
                    "name": "counterToken",
                    "type": "address",
                    "internalType": "address"
                  },
                  {
                    "name": "v3Fee",
                    "type": "uint24",
                    "internalType": "uint24"
                  }
                ]
              }
            ]
          },
          {
            "name": "extensions",
            "type": "tuple[]",
            "internalType": "struct IArtCoinsFactoryV2.ExtensionConfigV2[]",
            "components": [
              {
                "name": "extension",
                "type": "address",
                "internalType": "address"
              },
              {
                "name": "msgValue",
                "type": "uint256",
                "internalType": "uint256"
              },
              {
                "name": "extensionBps",
                "type": "uint16",
                "internalType": "uint16"
              },
              {
                "name": "extensionData",
                "type": "bytes",
                "internalType": "bytes"
              }
            ]
          }
        ]
      },
      {
        "name": "poolKey",
        "type": "tuple",
        "internalType": "struct PoolKey",
        "components": [
          {
            "name": "currency0",
            "type": "address",
            "internalType": "Currency"
          },
          {
            "name": "currency1",
            "type": "address",
            "internalType": "Currency"
          },
          {
            "name": "fee",
            "type": "uint24",
            "internalType": "uint24"
          },
          {
            "name": "tickSpacing",
            "type": "int24",
            "internalType": "int24"
          },
          {
            "name": "hooks",
            "type": "address",
            "internalType": "contract IHooks"
          }
        ]
      },
      {
        "name": "token",
        "type": "address",
        "internalType": "address"
      },
      {
        "name": "extensionSupply",
        "type": "uint256",
        "internalType": "uint256"
      },
      {
        "name": "extensionIndex",
        "type": "uint256",
        "internalType": "uint256"
      }
    ],
    "outputs": [],
    "stateMutability": "payable"
  },
  {
    "type": "function",
    "name": "supportsInterface",
    "inputs": [
      {
        "name": "interfaceId",
        "type": "bytes4",
        "internalType": "bytes4"
      }
    ],
    "outputs": [
      {
        "name": "",
        "type": "bool",
        "internalType": "bool"
      }
    ],
    "stateMutability": "view"
  },
  {
    "type": "event",
    "name": "AllocationClaimed",
    "inputs": [
      {
        "name": "token",
        "type": "address",
        "indexed": true,
        "internalType": "address"
      },
      {
        "name": "index",
        "type": "uint256",
        "indexed": true,
        "internalType": "uint256"
      },
      {
        "name": "beneficiary",
        "type": "address",
        "indexed": true,
        "internalType": "address"
      },
      {
        "name": "amount",
        "type": "uint256",
        "indexed": false,
        "internalType": "uint256"
      },
      {
        "name": "remainingAmount",
        "type": "uint256",
        "indexed": false,
        "internalType": "uint256"
      }
    ],
    "anonymous": false
  },
  {
    "type": "event",
    "name": "AllocationCreated",
    "inputs": [
      {
        "name": "token",
        "type": "address",
        "indexed": true,
        "internalType": "address"
      },
      {
        "name": "index",
        "type": "uint256",
        "indexed": true,
        "internalType": "uint256"
      },
      {
        "name": "beneficiary",
        "type": "address",
        "indexed": true,
        "internalType": "address"
      },
      {
        "name": "supply",
        "type": "uint256",
        "indexed": false,
        "internalType": "uint256"
      },
      {
        "name": "lockupEndTime",
        "type": "uint256",
        "indexed": false,
        "internalType": "uint256"
      },
      {
        "name": "vestingEndTime",
        "type": "uint256",
        "indexed": false,
        "internalType": "uint256"
      }
    ],
    "anonymous": false
  },
  {
    "type": "error",
    "name": "AllocationAlreadyExists",
    "inputs": []
  },
  {
    "type": "error",
    "name": "AllocationNotUnlocked",
    "inputs": []
  },
  {
    "type": "error",
    "name": "ConstantsMismatch",
    "inputs": [
      {
        "name": "module",
        "type": "address",
        "internalType": "address"
      }
    ]
  },
  {
    "type": "error",
    "name": "DurationTooLong",
    "inputs": []
  },
  {
    "type": "error",
    "name": "InvalidBeneficiary",
    "inputs": []
  },
  {
    "type": "error",
    "name": "InvalidExtensionData",
    "inputs": []
  },
  {
    "type": "error",
    "name": "InvalidMsgValue",
    "inputs": []
  },
  {
    "type": "error",
    "name": "InvalidVaultBps",
    "inputs": []
  },
  {
    "type": "error",
    "name": "NoBalanceToClaim",
    "inputs": []
  },
  {
    "type": "error",
    "name": "Unauthorized",
    "inputs": []
  },
  {
    "type": "error",
    "name": "VaultLockupDurationTooShort",
    "inputs": []
  },
  {
    "type": "error",
    "name": "VaultVestingDurationTooShort",
    "inputs": []
  },
  {
    "type": "error",
    "name": "WrongExtensionEntry",
    "inputs": []
  },
  {
    "type": "error",
    "name": "ZeroAddress",
    "inputs": []
  }
] as const;
