// Generates abi/{v1,v2}/*.ts from forge artifacts so the abi cannot drift from the contracts.
//
//   forge build --skip "test/**" --skip script     (from the repo root)
//   cd script-js && npm run gen:abi   write the files
//   cd script-js && npm run check:abi exit 1 when a committed file differs from the artifacts
//
// v2 entries come from the frozen interfaces (the deployed contracts implement them exactly), except the
// factory and the fee escrow: those come from the contract artifacts (ArtCoinsFactoryV2,
// ArtCoinsFeeEscrowV2), a strict superset of the interface that also carries the additive surface the site
// reads (minLpFee, defaultAllowed, tokenDeployer, owner, the additive errors). a check below fails when a
// contract abi ever loses an interface item.
// v1 entries from the contracts of the current mainnet stack (factory 0x4959...).
import { readFileSync, writeFileSync, existsSync, mkdirSync } from 'node:fs';
import { dirname, join, resolve } from 'node:path';
import { fileURLToPath } from 'node:url';

const here = dirname(fileURLToPath(import.meta.url));
const root = resolve(here, '..');
const out = join(root, 'foundry-out');
const dest = resolve(root, 'abi');
const check = process.argv.includes('--check');

/** [group, file name, artifact dir (the .sol file), contract name, export name, optional interface artifact the abi must contain] */
const TARGETS = [
  ['v2', 'factory', 'ArtCoinsFactoryV2.sol', 'ArtCoinsFactoryV2', 'factoryV2Abi', 'IArtCoinsFactoryV2.sol/IArtCoinsFactoryV2'],
  ['v2', 'hook', 'IArtCoinsHookV2.sol', 'IArtCoinsHookV2', 'hookV2Abi'],
  ['v2', 'token', 'IArtCoinsTokenV2.sol', 'IArtCoinsTokenV2', 'tokenV2Abi'],
  ['v2', 'locker', 'IArtCoinsLpLockerV2.sol', 'IArtCoinsLpLockerV2', 'lockerV2Abi'],
  ['v2', 'mevSkim', 'IArtCoinsMevSkimV2.sol', 'IArtCoinsMevSkimV2', 'mevSkimV2Abi'],
  ['v2', 'escrow', 'ArtCoinsFeeEscrowV2.sol', 'ArtCoinsFeeEscrowV2', 'escrowV2Abi', 'IArtCoinsFeeEscrowV2.sol/IArtCoinsFeeEscrowV2'],
  ['v2', 'devBuy', 'IArtCoinsUniv4EthDevBuyV2.sol', 'IArtCoinsUniv4EthDevBuyV2', 'devBuyV2Abi'],
  ['v2', 'vault', 'IArtCoinsVaultV2.sol', 'IArtCoinsVaultV2', 'vaultV2Abi'],
  ['v2', 'airdrop', 'IArtCoinsAirdropV2.sol', 'IArtCoinsAirdropV2', 'airdropV2Abi'],
  ['v1', 'factory', 'ArtCoinsFactory.sol', 'ArtCoinsFactory', 'factoryV1Abi'],
  ['v1', 'hook', 'ArtCoinsHookSkimFee.sol', 'ArtCoinsHookSkimFee', 'hookV1Abi'],
  ['v1', 'token', 'ArtCoinsToken.sol', 'ArtCoinsToken', 'tokenV1Abi'],
  ['v1', 'locker', 'ArtCoinsLpLocker.sol', 'ArtCoinsLpLocker', 'lockerV1Abi'],
  ['v1', 'mevLinearSkim', 'ArtCoinsMevLinearSkim.sol', 'ArtCoinsMevLinearSkim', 'mevLinearSkimV1Abi'],
];

let drift = 0;
const itemKey = (x) => `${x.type}:${x.name ?? ''}(${(x.inputs ?? []).map((i) => i.type).join(',')})`;

for (const [group, name, dir, contract, exp, mustContain] of TARGETS) {
  const artifact = join(out, dir, `${contract}.json`);
  if (!existsSync(artifact)) {
    console.error(`missing artifact ${artifact}; run forge build first`);
    process.exit(2);
  }
  const abi = JSON.parse(readFileSync(artifact, 'utf8')).abi.filter((x) => x.type !== 'constructor');
  if (mustContain) {
    const iface = join(out, `${mustContain}.json`);
    if (!existsSync(iface)) {
      console.error(`missing artifact ${iface}; run forge build first`);
      process.exit(2);
    }
    const have = new Set(abi.map(itemKey));
    const lost = JSON.parse(readFileSync(iface, 'utf8')).abi.filter((x) => x.type !== 'constructor' && !have.has(itemKey(x)));
    if (lost.length) {
      console.error(`${contract} abi lacks interface items: ${lost.map(itemKey).join(', ')}`);
      process.exit(2);
    }
  }
  const body =
    `// generated by script-js/gen-abis.mjs from ${dir}/${contract}.json, do not edit.\n` +
    `// regenerate: forge build (repo root) then cd script-js && npm run gen:abi\n` +
    `export const ${exp} = ${JSON.stringify(abi, null, 2)} as const;\n`;
  const file = join(dest, group, `${name}.ts`);
  mkdirSync(dirname(file), { recursive: true });
  const prev = existsSync(file) ? readFileSync(file, 'utf8') : null;
  if (check) {
    if (prev !== body) {
      drift++;
      console.error(`drift: ${file}`);
    }
  } else if (prev !== body) {
    writeFileSync(file, body);
    console.log(`wrote ${group}/${name}.ts (${abi.length} items)`);
  }
}
if (check && drift) process.exit(1);
if (check) console.log('abi files match artifacts');
